### ISSUE TITLE
Change local development environment setup to use sqlite instead of Postgres.

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#113]
One of the biggest hang-ups we find for new contributors is the ability to setup Postgres on their local machine. While others may find this task easy to do, others have a much steeper learning curve. 

My proposal is to create a way for contributors to use a sqlite db for their local dev environment instead. There are not as many configurations and will hopefully make it easier for those who want to contribute code get setup much faster!

**Comment by coreyd303** [comment]
Hi! I would love to help around here if I can, I have done some TA work with Rachel and Bree in Denver for GDI at Turing and would love to help with some of these issues. I would be happy to take a look at rolling over to SQLite from postgrSQL if thats cool . . . I would also be happy to take a look at the UX home button issue if thats cool?

**Comment by coreyd303** [comment]
In consideration of your comment though keep in mind there are limitations with deployment using SQLite, I am thinking specifically with Heroku . . . It might be work considering using SQLite for development and keeping PostgreSQL for production . . .

**Comment by DBNess** [comment]
Thanks @coreyd303! The idea @juliaelman so kindly introduced is to change **only development** to make environment setup easier for people unfamiliar with Postgres, not to change the Production settings. Hope that helps clarify. We are also not 100% wed to the idea of SQLite, so if there are any new methods you know of to bypass PostgreSQL install & speed up development environment setup, feel free to share them here.

**Comment by coreyd303** [comment]
@DBNess I think that SQLite is a sound solution for this, I mean there are other solutions, but SQLite plays well with Rails and development, and it pretty human friendly it seems like a good choice. Plus its a really easy change to make. Sorry I wasn't clear above, but yes for development only; what about test? I put in a PR with sqlite plugged in for development and test . . . I hope that's okay ?

**Comment by coreyd303** [comment]
@DBNess Hey, I think it is a great way to do it. I am noob status so I also don't have much in the way of other ideas. I know there are some other DB options to pick from, but the ones I can think of would probably come with issues much like postgres. Would you and @juliaelman think it would also be a good plan to switch test over to SQLite as well? I typically have kept those two the same, but I think that is more in my head that for any real reason.

**Comment by DBNess** [comment]
Thanks, @coreyd303! Switching test over as well is ideal because the test
database gets created locally to run rspec.

**Comment by kstack7** [comment]
Cleaned up with new PR in #141
