### ISSUE TITLE
Remove "home" link in main navigation

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#115]
It's most likely un-necessary to have a "home" link in the main navigation of the website. The GDI logo on the left links back to the homepage. Seems to be something most users understand, but am leaning on our UX experts for feedback on this too //cc  @cfarm @snkahn

**Comment by Cara-Jo** [comment]
I agree with removing it.

**Comment by corinnepw** [comment]
I second that. Also bringing in @alohaas for another UX opinion. :)

**Comment by alohaas** [comment]
Hey! 
I'm for its removal as well.

**Comment by coreyd303** [comment]
I would be happy to do this real quick :)

**Comment by juliaelman** [comment]
Fixed here #134
