### ISSUE TITLE
Add @kstack7 to CONTRIBUTORS.md

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#121]
@kstack7 has shown an immense amount of pull requests, reviews and overall support on this project! :fireworks: I propose to add her to our list of official contributors here: https://github.com/girldevelopit/gdi-new-site/blob/master/CONTRIBUTORS.md#contributors-1

- [x] Add Kristen Curtze
- [x] Hyperlink her name to her Github account here: https://github.com/kstack7

**Comment by juliaelman** [comment]
@corinnepw thanks for making the change! We generally don't close issues until they have a been reviewed by a person other than the PR author.

**Comment by corinnepw** [comment]
@juliaelman Great - thank you and sorry!

**Comment by juliaelman** [comment]
No worries @corinnepw! It looks like you went ahead and merged that change in. Next time, please feel free to ping someone in #website to review it. I know it's a minor change, but want to make sure we get in the habit of going through this process :D

**Comment by corinnepw** [comment]
@juliaelman Awesome! 100% agree. Thanks for implementing these best practices!
