### ISSUE TITLE
"bundle install" times out while trying to check out active_admin

### ISSUE THREAD

**Issue by cassiehelms** [girldevelopit/gdi-new-site#128]
Doing "bundle install" during environment set up on Mac OSX 10.7.5 sometimes results in a git timeout on the active_admin repo.  The error looks like the following:

======
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Operation timed out

Git error: command `git clone 'git://github.com/gregbell/active_admin.git'
"/Users/cassie/.rvm/gems/ruby-2.1.2/cache/bundler/git/active_admin-d67faab65e9b74efbc8efb4a777a851e9f78b2ca" --bare --no-hardlinks --quiet` in directory
/Users/cassie/coderdayofservice/girldevelopit/gdi-new-site has failed.
======

This does not appear to be related to being behind a proxy (which I am not) or related to my ~/.gitconfig file.

**Comment by cassiehelms** [comment]
I noticed in my environment, this command was successful:
git clone https://github.com/gregbell/active_admin.git
while this one was not:
git clone git://github.com/gregbell/active_admin.git

I got past this Timeout by doing the following git command:
git config --global url."https://".insteadOf git://

**Comment by cassiehelms** [comment]
We suspect this is related to the guest wifi we are using perhaps filtering ssh packets related to the git clone git:// request with a firewall or similar.

**Comment by juliaelman** [comment]
@cassiehelms thank you for submitting this issue! It is most likely the wifi connection, but @kstack7 is going to take a deeper look for confirm. :tada:

**Comment by kstack7** [comment]
Anyone want to test one line for me? I think I have a solution.

**Comment by kstack7** [comment]
K I got a tester and he had a successful install. Going to push my changes in a PR.

**Comment by kstack7** [comment]
Woops forgot I didn't merge the changes yet! Anyone wanna review my #137 ??

**Comment by juliaelman** [comment]
Fixed with #137
