### ISSUE TITLE
Add page title to title element

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#131]
Currently, all the pages have the same HTML title, Girl Develop It. For better bookmarks/SEO, add the page title to the HTML title. 

For example:
Girl Develop It - About
Girl Develop It - Donate

Open to format suggestions.

**Comment by AndyLampert** [comment]
I'll work on this!

**Comment by Cara-Jo** [comment]
Go @AndyLampert! I'm good with the above format!

**Comment by AndyLampert** [comment]
Cool if we do it like this:

About - Girl Develop It
Donate - Girl Develop It

...etc? 

Putting the page title first seems to be the the standard for page optimization. Cool?
http://moz.com/learn/seo/title-tag

**Comment by juliaelman** [comment]
@AndyLampert seems okay, but it seems like we'd want to optimize "Girl Develop It" first and foremost... no?

**Comment by Cara-Jo** [comment]
I was going to make this same suggestion - glad you pointed it out @AndyLampert

**Comment by Cara-Jo** [comment]
Alternativly - we could do something like: 

GDI: Donate - Girl Develop It
GDI: About - Girl Develop It

Just throwing some ideas out there.

**Comment by AndyLampert** [comment]
@Cara-Jo @juliaelman 

My vote goes for:
About - Girl Develop It
Donate - Girl Develop It 

And "GDI: Donate - Girl Develop It" seems a little repetitive to me, but I'm happy to do whichever, lemme know!

**Comment by Cara-Jo** [comment]
Now that I see it - you're totally right. It is a bit redundant

**Comment by juliaelman** [comment]
@AndyLampert cool! :+1: on your proposed changes. We can test to see how well our hits are in regards to these titles and/or if it's an issue laters.

**Comment by Cara-Jo** [comment]
Thanks @AndyLampert for doing that research! :+1: :100:

**Comment by thejinxters** [comment]
check out the PR https://github.com/girldevelopit/gdi-new-site/pull/143

**Comment by thejinxters** [comment]
oh.. and forgot the emoji :womans_hat:

**Comment by AndyLampert** [comment]
:bow: @Cara-Jo

**Comment by juliaelman** [comment]
Fixed with #143.
