### ISSUE TITLE
Update Rails from 4.1.4 to 4.1.9

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-new-site#133]
@therufs, David (@bayendor in Slack) was mentioning that we should push to 4.1.9 in order to take advantage of some security updates and patches. Is there a reason not to do this? Same question goes for specifying gem versions.

**Comment by coreyd303** [comment]
From what I know on semantic versioning on these there shouldn't be any down sides. I would be happy to work on this if it is wanted . . .

**Comment by coreyd303** [comment]
4.1.9 seems to be a-okay. I'll put up a PR for review

**Comment by bayendor** [comment]
This issue was resolved with PR #172.  Should we close it out?

**Comment by kstack7** [comment]
YES! Thank you. I was watching the latest deploy and didn't come back here. We appreciate your help, @bayendor
