### ISSUE TITLE
Establish redirect from /materials to /curriculum

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#135]
So incoming links to /materials make it to the new page. Same for any page with an old site to new site URL switch.

**Comment by Roenok** [comment]
Here's another one: /codeofconduct to /code-of-conduct

**Comment by juliaelman** [comment]
@Roenok can you open another PR for the Code of Conduct routing? Thanks!

**Comment by Roenok** [comment]
@juliaelman Done, as https://github.com/girldevelopit/gdi-new-site/issues/138

**Comment by juliaelman** [comment]
:dancer: @Roenok

**Comment by Cara-Jo** [comment]
Can I ask why changing the URL to curriculum? I have a hard time spelling it, as I'm sure others do as well. I would hate for that to be a barrier for those looking to get materials from us.

**Comment by kstack7** [comment]
We're not :) I checked this multiple times too outta confusion. We're doing '/materials'

**Comment by Cara-Jo** [comment]
GOOD. I can't spell that word to save my life.

**Comment by kstack7** [comment]
Haha yeah i was telling @juliaelman I'd have to open an issue solely for error-checking the spelling throughout the code haha

**Comment by Roenok** [comment]
Wrong button there, sorry. Ignore the close.

**Comment by Roenok** [comment]
There, that's the label I wanted. Now closing. We have updated #66 to use materials, so this redirect is no longer needed.
