### ISSUE TITLE
Create list of curriculum for new site (content)

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#136]
As a companion to https://github.com/girldevelopit/gdi-new-site/issues/66, create a list of curriculum for the new site. Each needs:

* Title
* Icon (from http://mfizz.com/oss/font-mfizz for now)
* Long description
* Short description
* Links to slides on git pages
* Links to practice files and homework (optional)
* Link to GitHub repo

**Comment by Cara-Jo** [comment]
I've got a large collection of svg icons for all the techs - just curious which one's were going to have on the page. Do you have a list started so I can start plugging away at the icons?

**Comment by kstack7** [comment]
you can always upload the icons for the class in the admin side

**Comment by Roenok** [comment]
@Cara-Jo Minimum list:

Introduction to Web Concepts
Web Accessibility
Intro to Git and Github
Introduction to HTML/CSS
Intermediate HTML/CSS
Introduction to JavaScript
Introduction to jQuery

Hoping to get the Python and WordPress libraries cleaned up and posted as well, but it may be a few days post-launch. I have some simple PNGs for everything if needed, but more beautiful options are always appreciated. They need to be actual image files to work with the current active admin interface. We can talk about adding a way to icon-ify them in a future release.

**Comment by Cara-Jo** [comment]
Yeah I just want to have the icons available for people to upload. :) Thanks for the list!

**Comment by Cara-Jo** [comment]
Here's a folder with a bunch of icons in SVG and then exported in the navy color in .PNG format: https://www.dropbox.com/s/h008rmsup2x6r5r/materials-icons.zip?dl=0 

@Roenok I can also e-mail this to you if it doesn't work for you. Excuse my poor artboard layout on materials.ai :P

**Comment by juliaelman** [comment]
@Roenok checking in to see how the progress is moving along for this one. Do you need any help with anything?

**Comment by Roenok** [comment]
@juliaelman Core stuff is in, so we can probably close. Some other stuff is pending review, not ready to post.

**Comment by juliaelman** [comment]
@Roenok cool! I close. :tada: Thank you!
