### ISSUE TITLE
Establish redirect from /codeofconduct to /code-of-conduct

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#138]
So incoming links to /codeofconduct make it to the new page.

**Comment by AndyLampert** [comment]
I'm on it!

**Comment by thejinxters** [comment]
Made PR https://github.com/girldevelopit/gdi-new-site/pull/149
@AndyLampert

**Comment by thejinxters** [comment]
:shipit:

**Comment by kstack7** [comment]
Merged with #149
