### ISSUE TITLE
links at the bottom of /code-of-conduct need to have page context as the link instead of the full url

### ISSUE THREAD

**Issue by AndyLampert** [girldevelopit/gdi-new-site#154]
Contact information for your local Chapter Leader can be found on http://girl-develop-it.herokuapp.com/chapters

=>something like this
Contact information for your local Chapter Leader can be found on <a href="#">our chapter page</a>.

https://www.dropbox.com/s/qbs4svemk5binjs/Screenshot%202015-01-31%2015.46.34.png?dl=0

**Comment by thejinxters** [comment]
PR #155 fixes this @AndyLampert
