### ISSUE TITLE
Dual use of image magick / rmagick in gem file

### ISSUE THREAD

**Issue by bayendor** [girldevelopit/gdi-new-site#159]
We seem to have two image compression tools in the gem file.  Unless we are using `jruby` do we need `rmagick`?

**Comment by kstack7** [comment]
rmagick requires imagemagick to run, I thought?

**Comment by bayendor** [comment]
@kstack7, my apologies, you are of course correct.  What I meant to call out was the apparent redundant requirement of both `MiniMagick` and `RMagick` in the gem file.

According to the carrier wave documentation: "Some documentation refers to RMagick instead of MiniMagick but MiniMagick is recommended."  And the gem spec for carrier wave only require  rMagick  for `jruby`.  

It's not critical, but I was parsing the Gemfile and wondered why both were included.

**Comment by kstack7** [comment]
Ah got it! :+1: We will likely encounter this while improving our installation process (Ex: #130 ) so thank you @bayendor for bringing it to our attention :) Always helps to keep things simple and straight-forward.

**Comment by juliaelman** [comment]
Seems like #130 is a duplicate issue to this? @kstack7 @bayendor if so, please let me know so we can mark correctly and move forward.

**Comment by kstack7** [comment]
@juliaelman they're slightly different. We could merge the two concepts for general installation improvements like using homebrew to get imagemagick etc.

**Comment by bayendor** [comment]
@juliaelman They are related, I cross-commented in #130 regarding this.  I've been working on a clean install / upgrade path related to #133, and `rmagick` is not installed or required when bundling with `carrier wave`, `mini_magick` gets loaded instead.

**Comment by juliaelman** [comment]
@bayendor right on! Looking fwd to reviewing your PR and let us know if you need anything else \o/

**Comment by tnbKristi** [comment]
Awesome @bayendor  - tried to do a fresh install tonight to help out, and got held up on this config issue. Look forward to that merge. :)

**Comment by bayendor** [comment]
I believe this issue was resolved with PR #172. Should we close it out?

**Comment by kstack7** [comment]
Yes! Thanks again, @bayendor :)
