### ISSUE TITLE
Missing state images on /chapters page

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#160]
We are currently missing the following state images on the /chapters page:

- Arizona
- Georgia
- Indiana
- Kentucky
- North Dakota
- Virginia

Here are the steps needed to make this happen:

- [x] Created images using the following .eps file: http://cl.ly/ZYSZ/download/us-map.eps
- [x] Size them to the correct fixed proportions of 400px width x 350px height.
- [x] Save them with their corresponding states name in all lower case.
- [x] Add them to the `/app/assets/images/state_map` folder.

**Comment by Roenok** [comment]
I can grab this one; it will be good to practice my Illustrator skills

**Comment by Roenok** [comment]
Added in pull request #181

**Comment by kstack7** [comment]
Merged the new files, but Kentucky caught us off guard. I submitted PR #185 to fix the typo. All set otherwise! They look great. Nice job, @Cara-Jo

**Comment by juliaelman** [comment]
DONEZ! Thanks everyone for your contributions and making sure we have all states covered.

**Comment by kstack7** [comment]
:+1:
