### ISSUE TITLE
Enable leaders role to edit bios for their chapter

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#161]
Currently, Active Admin users with the `leaders` role cannot edit bios for their chapter. We'd like to create the ability for these users to to do and make it easier for them to update, edit and remove information about their leaders in their pages.

**Comment by kstack7** [comment]
I know how to enable this so any leader can edit ANY chapter/bio, but I'm trying to make it so that you can only edit those tied to your chapter. I can push the wide open edit permissions for the sake of productivity though? Just didn't want to add confusion or have anyone accidentally overwrite others' details.

**Comment by kstack7** [comment]
@juliaelman I may need to talk about the db with you soon. I created a leader-level user and changed the permissions so they can only manage/view records related to the chapter ID#...this definitely simplifies the dashboard/navigation, but I want to make sure this is the direction we'd like to go.

**Comment by staceyturnage** [comment]
I would like to edit bios & rearrange the information on my chapter page....HELP!  Need a crash course on "how to" do that. Currently my new page indicates we have 3 chapter leaders and that's incorrect...HELP!!

**Comment by kstack7** [comment]
@staceyturnage: @juliaelman and I are going over this tonight and I may push some changes that will greatly simplify this ordeal. I can follow-up with you afterwards to see how your chapter is looking. Sound good?

**Comment by staceyturnage** [comment]
Sounds great!

Let me know what my next steps are!

Thanks,

Stacey

On Mon, Feb 2, 2015 at 2:48 PM, kstack7 <notifications@github.com> wrote:

> @staceyturnage <https://github.com/staceyturnage>: @juliaelman
> <https://github.com/juliaelman> and I are going over this tonight and I
> may push some changes that will greatly simplify this ordeal. I can
> follow-up with you afterwards to see how your chapter is looking. Sound
> good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girldevelopit/gdi-new-site/issues/161#issuecomment-72534576>
> .
>



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage

**Comment by juliaelman** [comment]
PR #169 noted.

**Comment by juliaelman** [comment]
Fixed with #169 by the amazing @kstack7! \o/

**Comment by juliaelman** [comment]
Issue was with Heroku being down today and had nothing to to with our code base. :wink:
