### ISSUE TITLE
Add "Fork me on Github" ribbon to website

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#162]
In an effort to gain more contributors to this code base, it would nice to have badge that makes folks aware that the website is an open source project. 

Here are the steps to take to make it happen:

- [x] Select the code from [https://github.com/blog/273-github-ribbons](https://github.com/blog/273-github-ribbons) with ribbon that matches the color scheme for the new website
- [x] Add the ribbon to https://github.com/girldevelopit/gdi-new-site/blob/master/app/views/layouts/application.html.erb

**Comment by Cara-Jo** [comment]
On it! :muscle: :sparkles: :penguin:

**Comment by Cara-Jo** [comment]
SEe PR #184 :penguin:

**Comment by juliaelman** [comment]
Fixed!
