### ISSUE TITLE
Change Mandrill settings to point to girldevelopit.com

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#165]
Currently, we have the DNS as the default Heroku application name (girl-develop-it) for our Mandrill settings. I am pretty sure we'll need to change that once we switch the DNS to points to  girldevelopit.com on #61.

**Comment by kstack7** [comment]
Yup! I'd be happy to get those TXT files set in place for when we want them. Just saves one last-minute adjustment for the launch plus gives time to propagate :)

**Comment by kstack7** [comment]
We are verified with Mandrill yaaaayy!

![screen shot 2015-02-13 at 11 52 06 pm](https://cloud.githubusercontent.com/assets/6612770/6198609/6738eb86-b3db-11e4-89e4-6b37f20dea59.png)

**Comment by kstack7** [comment]
The DKIM/SPF need a bittle to propagate, but we won't notice a change :)
