### ISSUE TITLE
Add chapter level sponsors to chapter pages.

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#171]
Currently, chapter sponsors do not show up on the chapter level pages. This will take a bit of design help for layout + template additions to be able to make this work. Very design friendly!

**Comment by Roenok** [comment]
30 second mockup! We can place logos and names in an aside below the chapter name on desktop:
![image](https://cloud.githubusercontent.com/assets/925963/6027225/bb36b2ca-abae-11e4-94bc-d620f07bb15d.png)

Then small-tile logo on mobile, dropping the name for space:
![image](https://cloud.githubusercontent.com/assets/925963/6027314/256540e4-abaf-11e4-96cd-2fd28b0355fb.png)

Anyone else have suggestions?

**Comment by minamarkham** [comment]
I like the mockup. Once you've settled on a design, feel free to assign this to me :grin:

**Comment by Roenok** [comment]
I think this is the only idea so far. If you think you can run with it, please do!

**Comment by minamarkham** [comment]
Assign to me please :smiley:

**Comment by juliaelman** [comment]
@minamarkham assigned!

**Comment by beckysingson** [comment]
+1 priority, gracias @minamarkham
