### ISSUE TITLE
Broken links in no events fallback

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#178]
On chapter pages, there is a fallback paragraph for chapters with no scheduled events:
Sadly, no meetups are currently scheduled for this Chapter. Join our meetup group to be notified when a new meetup is happening. Thanks for visiting us!

"Join our meetup group" should link to the meetup group, same as the Join us link in the aside. Instead, it links to "http://meetup.%20com/chapter-slug"

Knock out the space, it it should work. 

See https://girl-develop-it.herokuapp.com/chapters/west-palm-beach for an example.

**Comment by kstack7** [comment]
On it :)

**Comment by kstack7** [comment]
PR #180

**Comment by juliaelman** [comment]
Fixed! :football:
