### ISSUE TITLE
Miami link is incorrect on Chapters page

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#179]
On the homepage map, Miami links to https://girl-develop-it.herokuapp.com/chapters/miami, which works. However, on the Chapters page, the link points to https://girl-develop-it.herokuapp.com/chapters/miami-fort-lauderdale, which throws a 404.

**Comment by kstack7** [comment]
hmmmm @juliaelman I bet this is another db thing. I bet the name changed after the first creation because my local files have "Miami" as the chapter name. That slug is an index soooo may have to run that again?

**Comment by kstack7** [comment]
Or set it back to Miami in the db hahah ::easy button::

**Comment by juliaelman** [comment]
@kstack7 I think the best solution would be to set the route up correctly. Not sure why it is using "miami" instead of "miami-fort-lauderdale" and/or/how/why that changed. We have a few chapters which are similar to this and seem to work fine.

**Comment by kstack7** [comment]
Yeah that makes sense. I just figured it was a name change after the migration or something that didn't settle right. I still want to see where it's coming from, as it seems almost cached or like old data.

**Comment by kstack7** [comment]
So I ended up deleting the old Miami and creating a new one. The URL now works with miami-fort-lauderdale, but it's now out of alphabetical order in the Florida list. I'm thinking this is something with the database and I'll have to dig deeper to see how to "refresh" things.

**Comment by kstack7** [comment]
Got it! PR coming...

**Comment by kstack7** [comment]
Fixed in PR #191
