### ISSUE TITLE
Menu of upcoming & recent classes/events

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#186]
Description
A menu of the upcoming &/or past classes/events. Where the user can click on the hyperlink and get a short blurb on the class instead of a link taking you to the meet up page. 

Ask
I would like the user to be able to click on the hyperlink next to the upcoming &/or past classes to get a quick blurb of the description of the class. Not a link taking the user to Meet up. 

To Do
- [ ] Create a drop down box w/ hyperlinks
- [ ] Create a menu on the side of the chapter pages

Additional Info
This would just be a quick place for a user to see what the chapter has been up to without leaving the GDI website.

**Comment by juliaelman** [comment]
@staceyturnage I am not 100% sure it's the best use of the page to add past classes. Meetup keeps an archive on hand and would like to not re-create too much content on the site.

Also, I am not sure that we need to add any extra verbiage, as we do post a rather large chunk of text on the page as is.

@kstack7 thoughts?

**Comment by kstack7** [comment]
There is actually a great discussion on this over in #233 so these two can combine into one discussion as we move forward. The gist of it being that it'd be good to show "sold out" courses when possible but still three open courses without overwhelming the space.

**Comment by juliaelman** [comment]
@kstack7 cool! Did you want to close this issue and add to the discussion on the other issue or... ? I feel like this issue has a few more nuances, but will leave it up to you on you'd like to move forward.

**Comment by kstack7** [comment]
@staceyturnage let's move this over to #233 since there is more traction over there. It'd be great to keep all our input on one issue so we can cover more in one merge :)
