### ISSUE TITLE
Fix sizing for maps on the Chapter Pages 

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#187]
Description
The maps appear to be large 

Ask
Can the maps be smaller?

To Do
- [x] Don't eliminate the maps make them smaller 

Additional Info
I get a map is helpful however the map appears to take up a lot of room on the chapter page.

**Comment by staceyturnage** [comment]
Or put the map below the class description.  It appears that the map is the focus when the class should be the focus.

**Comment by kstack7** [comment]
We actually just swapped this over night...the map was out of place unless under the address...and then the RSVP button would be on it's own if not by the description...things to consider for sure!

**Comment by Cara-Jo** [comment]
How about we reduce the height of the map by about 200px? 
![screenshot 2015-02-14 12 06 25](https://cloud.githubusercontent.com/assets/180763/6200735/4c8dddfc-b442-11e4-809d-318731957902.png)

**Comment by kstack7** [comment]
Ooo I like that! Beats reducing the width...

**Comment by Cara-Jo** [comment]
Alternate layout entirely, gets all the content right there in one spot:

![screenshot 2015-02-14 12 19 51](https://cloud.githubusercontent.com/assets/180763/6200770/d94f1e62-b443-11e4-9b4a-f32886d61bdb.png)

**Comment by Cara-Jo** [comment]
Optionally, we could zoom the map out to 14 instead of 16 and get more of the surrounding area.
![screenshot 2015-02-14 12 21 37](https://cloud.githubusercontent.com/assets/180763/6200779/40d66d7e-b444-11e4-8718-b6f1bff7ff20.png)

**Comment by kstack7** [comment]
May want to view a few examples of those side-by-side/new suggestion...could start to look uneven as descriptions and addresses change in length.

**Comment by staceyturnage** [comment]
I like the 14 @Cara-Jo

**Comment by staceyturnage** [comment]
The alternate layout with all the information in one shot.

**Comment by beckysingson** [comment]
+1 to @Cara-Jo's recommendation here with side by side & 14 zoom

**Comment by techibis** [comment]
+1 to @Cara-Jo's recommendation here with side by side & 14 zoom
This is important to me.  Will help give my classes more visibility

**Comment by kstack7** [comment]
Hey @Cara-Jo did you try this on smaller/mobile platforms to see how it translates? Curious if it gets all wonky outside of a desktop width...we can start to move this forward and tack on the "sold out" issue #233 from there

**Comment by Cara-Jo** [comment]
They just stack in the same order.

**Comment by juliaelman** [comment]
@Cara-Jo okay to assign to you? Looks like you've got a solve working locally \o/

**Comment by Cara-Jo** [comment]
On it!

**Comment by pamelafox** [comment]
Hello! Our chapter uses the meetup setting " Only my members can see where this Meetup is happening", however the maps still display. We hide location in case of creepsters, we try to make it a little less obvious where to find us, and the maps make it really easy. Can we have the chapter pages obey that setting, or remove the maps for now?

**Comment by juliaelman** [comment]
@pamelafox thanks for pointing this out! Would you mind opening another issue for this specific issue and use the following template in #83? @kstack7 has a solve + would rather have it associated with it's own issue.

**Comment by juliaelman** [comment]
Just changed the title of this issue to be more specific on what is being asked for.

**Comment by minamarkham** [comment]
Creating two layouts; one with maps and one without, as shown here: https://github.com/girldevelopit/gdi-new-site/issues/248#issuecomment-74721817

**Comment by minamarkham** [comment]
or here: 

![screen shot 2015-02-17 at 8 59 35 pm](https://cloud.githubusercontent.com/assets/876210/6241768/868703c8-b6e8-11e4-9a94-35f8ef5e4476.png)

I added in some of the changes from @Cara-Jo https://github.com/girldevelopit/gdi-new-site/pull/246 as well. 

Will add sold out label in another issue.
