### ISSUE TITLE
Alphabetical Order 

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#188]
Description
The chapter cities are not in alphabetical order for Ohio and Texas 

Ask
Reflect the chapter cities in alphabetical order for Ohio and Texas 

To Do
- [x] Ohio - Cincinnati, Columbus, Toledo 
- [x] Texas - Austin, Dallas/FW, Houston 

Additional Info
The other chapters appear to be in alphabetical order under each state.

**Comment by kstack7** [comment]
@staceyturnage I'm exploring this one alongside the miami slug issue in #179 ...will keep you posted

**Comment by kstack7** [comment]
Fixed in PR #191
