### ISSUE TITLE
Updating computing related stat on the main homepage

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#190]
**Description**
The women in tech stats on the home page require updating. It is currently at 25%, but has since changed since the original stat from 2011.

**Ask**
There are more current statistics from the Bureau of Labor Department. 

**Additional Info**
The stats on the page are from 2011 there are more recent stats from 2013.  
http://www.bls.gov/cps/cpsaat11.htm
![screen shot 2015-02-06 at 6 44 37 pm](https://cloud.githubusercontent.com/assets/8386527/6089941/ff33a56c-ae30-11e4-894f-db0b4bce6b6e.png)
![screen shot 2015-02-06 at 6 42 46 pm](https://cloud.githubusercontent.com/assets/8386527/6089943/05436bae-ae31-11e4-8264-50bc8bab0894.png)

**Comment by staceyturnage** [comment]
I posted the second screen shots so the column headings on the page. Here's the link to the Bureau of Labor website http://www.bls.gov/cps/cpsaat11.htm

**Comment by staceyturnage** [comment]
Computer Programmers 23.0%
Software Developers, applications & systems software 19.7% 
Web Developers 39.5%

**Comment by juliaelman** [comment]
@staceyturnage I think we need to be a bit more specific on the numbers you think need to be changed on the homepage. I am going to list the numbers below and would appreciate you specifying what exactly needs to be swapped out where - thanks!

- Women hold only **25%** of the **3,816,000** 
- Women obtain **58% of bachelor’s degrees** in the U.S, but less than **18% of those degrees** are in computer science. **(Compared to 1984, when women earned 37%)**
- Tech companies with more women in management have a **34% higher return of investment.**

**Comment by staceyturnage** [comment]
@juliaelman Ok I confirmed the following number should be: 

Women hold only 35.2% of web development jobs. 

I couldn't find a total number of jobs.

**Comment by staceyturnage** [comment]
I got the information from the Bureau of Labor Stats. The link is above.

**Comment by staceyturnage** [comment]
Here's where the current information is located, so you maybe able to have the all up number remain the same but the percentage changed...http://www.ncwit.org/blog/did-you-know-demographics-technical-women

**Comment by juliaelman** [comment]
@staceyturnage hrmmm... I doubt that the number of jobs has stayed the same and don't want to assume anything. We need to find another source with the official numbers that we can post on the homepage.

@DBNess would love you input on this and what is a good reliable source to find these numbers (when you get a chance)!

**Comment by staceyturnage** [comment]
Baffles me why the Bureau of Labor stats doesn't have an total number and maybe it does and I may have missed it but that was my point earlier if the percentage has changed surely the number of jobs has changed as well they go hand in hand.

**Comment by juliaelman** [comment]
@corinnepw would love you help on this one to check on updated numbers for the homepage stats. The one's we currently have are for 2013.

**Comment by corinnepw** [comment]
Hi all! Got the latest stats from our research partner, National Center for Women & IT:
http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf & http://www.ncwit.org/sites/default/files/resources/impactgenderdiversitytechbusinessperformance_print.pdf & http://www.ncwit.org/sites/default/files/resources/ncwitfactsheet.pdf

I'm comfortable using the following updated stats:
- Women hold only *26%* of the approximately four million computing related occupations in the US.
- Women obtain *57%* of bachelor’s degrees in the U.S, but fewer than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%) - **I think the displayed percentage number here should be the 18% though, not 57%**
- Tech companies with more women in management have a 34% higher return of investment. **This one remains the same**

**Comment by juliaelman** [comment]
@corinnepw sold! I vote sendinf to NCWIT resources, but am not sure we need to cite. Going to submit a PR for updating the stats for now until I hear further from you and/or @DBNess!

**Comment by corinnepw** [comment]
@juliaelman how about we cite (in a smaller size) and link the citation to NCWIT. 

I know we're not using Bootstrap, but this is what I'm thinking [scroll down to small headings](http://getbootstrap.com/css/#type-headings). Does that make sense?

- Women hold only 26% of the approximately four million computing related occupations in the US. [U.S. Department of Labor, Bureau of Labor Statistics, 2013 (Occupational Category: 15–0000)](http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf) 
- Women obtain 57% of bachelor’s degrees in the U.S, but fewer than 18% of those degrees are in computer science. (Compared to 1984, when women earned 37%) [National Center for Education Statistics (NCES), 2012 (CIP 11)](http://www.ncwit.org/sites/default/files/resources/btn_02282014web.pdf)
- Tech companies with more women in management have a 34% higher return of investment. [National Center for Women and IT Fact Sheet](http://www.ncwit.org/sites/default/files/resources/ncwitfactsheet.pdf)

**Comment by juliaelman** [comment]
@corinnepw that works for me! Thanks for the detailed docs to clarify the linkage and how you would like it to work. Super helpful!

**Comment by DBNess** [comment]
:raised_hands: looks great!! Thanks, ladies!
