### ISSUE TITLE
Add further styling to /materials/<material-detail/ page

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#193]
**Description**
Currently, the detail page for materials is not well styled and could use some design :heart: 

**Ask**
Create a better designed responsive layout for material detail page (see attached screenshot for reference)

**To-Do**
- [ ] Add new styling to app/assets/materials.css.scss
- [ ] Create responsive styling too. \o/

**Additional Info**
Check out #175 for the current state and/or other information about the materials page.

**Comment by gorork** [comment]
@juliaelman Will the structure of the detail page be the same:
- header
- description
- list of slides
- list of links
- link to github
?

**Comment by Cara-Jo** [comment]
I've put on my SASS pants and I'm on the case. :jeans: :sparkles:

**Comment by juliaelman** [comment]
@gorork I think that would be a good start, but is really up to the designers opinion. Also, check out the following repo + style guide for reference too:

- https://github.com/girldevelopit/gdi-website-styleguide
- http://girldevelopit.github.io/gdi-website-styleguide/

**Comment by juliaelman** [comment]
@Cara-Jo assigning to you and your :jeans:

**Comment by kstack7** [comment]
Set in #209 :)
