### ISSUE TITLE
Typos & Sentence Structure 

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#194]
Description
Typo & sentence structure "You are free tos hare and adapt these materials." 

Ask
Reword this sentence "you are free to adapt these materials". https://girl-develop-it.herokuapp.com/materials

To Do
-  [ ] Reword the sentence 

Additional Info
The type on this page needs to be formatted.

**Comment by Roenok** [comment]
Bonus fix, while you are in the template: add this link to "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)" https://creativecommons.org/licenses/by-nc-sa/4.0/

The formatting would be improved by switching to either left align or a single paragraph.

**Comment by Cara-Jo** [comment]
On this as well, since I'm in the template now. :jeans: :sparkles:

**Comment by kstack7** [comment]
2 :bird: 1 :moyai: (that's as close to stone as it gets, people)

**Comment by kstack7** [comment]
:bird: :bird: :boom: :moyai:

**Comment by kstack7** [comment]
Fixed in #209
