### ISSUE TITLE
Separate Boulder/Denver Chapters

### ISSUE THREAD

**Issue by breethomas** [girldevelopit/gdi-new-site#195]
Description
The Boulder and Denver chapters are currently listed as one chapter, "Boulder/Denver". The Boulder/Denver team would like to give each of Boulder and Denver their own individual listings within the new website.

Ask
Update the Boulder chapter with a slug that reads just 'boulder' instead of 'boulder-denver'. 
Add the Denver chapter to the website.

To Do
- [x] Revise the current Boulder page slug to reflect 'boulder' when it links to that chapter's show page
- [x] Add Denver as an individual chapter to Colorado

**Comment by juliaelman** [comment]
@breethomas Thanks for submitting this issue! :+1:  

It will most likely take a bit more work than updating the chapter name in the admin (e.g. running a database migration). Not sure that we'll be able to accomplish prior to launch and have switched the name of the Boulder chapter back to Boulder/Denver for now. Hang tight!

**Comment by breethomas** [comment]
Maybe I didn't fully understand the format of the "To Do" part in the issue. I realize it will take more than what is listed there, although I'm not familiar enough with the code base to list out the specific technical tasks step-by-step. I'd happily pair with someone on it if that is an option. Let me know.

**Comment by breethomas** [comment]
@juliaelman what if I submit a PR with a "AddDenverChapter" migration with this (is that right and/or helpful?):

```

class AddDenverChapter < ActiveRecord::Migration
  def up
    Chapter.create!(chapter: 'Denver', slug: 'denver', latitude: 39.737010, longitude: -104.996338)
    AdminUser.find(email: 'bree@girldevelopit.com').first.update_attributes(chapter: Chapter.find_by_slug('denver'))
  end

  def down
    Chapter.find_by_slug('denver').destroy
    AdminUser.find(email: 'bree@girldevelopit.com').first.update_attributes(chapter: Chapter.find_by_slug('boulder-denver'))
  end
end
```

**Comment by juliaelman** [comment]
@kstack7 thoughts?

**Comment by kstack7** [comment]
Part of me wants to create a brand new boulder with a brand new denver...can always shift the bios/sponsors to the new chapter as needed. Just seems a bit easier (albeit slight busy work) vs. messing with migration unless we can get a db guru on here to present the super easy fix haha

**Comment by breethomas** [comment]
@kstack7 well...I do work w/ 5 db gurus in my regular day job. :smile: 

The current boulder-denver chapter on the live site only contains bios/instructors for the boulder crew. Denver is not represented right now, except for Meetup events. Boulder and Denver ARE separate chapters, but we share meetup ID/page, so our members can easily choose classes between the closely located cities. I'm happy to approach it in whatever way you think best (adding them both net new, or however).

My day job team (Mode Set) is happy to help us out a bit on this front. Wondering if you want to do any one of the following:
- give me heroku access so we can pull a pgbackup, verify the migration runs without issue locally
- give me a copy of the db, encrypted and sent over slack or some other medium
- provide access to a follower database on heroku that we could create a backup from and that you could destroy after we're done.

Mode Set are heroku experts, and would do an infrastructure audit for GDI to make sure we are taking advantage of the free platform services, like backups, if that is of any interest? (They were just throwing out ideas as I was chatting with them on this stuff).

**Comment by kstack7** [comment]
Woo @breethomas thanks for this offer! I'd love to run it by the rest of the website crew, as we're still fresh out the gate with this launch.

I think we need a bit of "order of events" first before letting Mode Set attack. @juliaelman is currently working on setting up a staging/production instances (#249) of the site so we can avoid using JUST 'master'...I'm thinking we could leverage that staging side for this and that should reduce the need for exchanging all our data back and forth.

Does this good to you?

**Comment by breethomas** [comment]
@kstack7 sure, sounds good. let me know at what point you need anything from me. I just want to make sure this issue stays top of mind so we can get Boulder and Denver represented correctly on the shiny new site. :heart: :smile_cat: and thanks for all your hardwork and prompt replies!

**Comment by kstack7** [comment]
Of course, @breethomas :) That's a bit why I suggested the busy work of just adding new/moving folks. It's not THAT daunting and it could be done in the later hours. That way you can get your proper Denver setup by tomorrow if you'd like! I'd be happy to help. I did it locally last night and it was fine. Just need to have your bios/info ready to roll.

**Comment by juliaelman** [comment]
@breethomas thanks for the offer to have Mode Set help out with the change! I think it does not need to be as complicated as we're making this and 100% agree with @kstack7 on how she'd like to move forward.

As for receiving a pgbackup of our production database, it is definitely something that we consider best practices. I am sure your team at Mode Set would agree to this too and the security issues it raises. 

@breethomas @Cara-Jo there are now separate pages for both Boulder and Denver. They both use the same Meetup ID.

[https://www.girldevelopit.com/chapters/boulder](https://www.girldevelopit.com/chapters/boulder)
[https://www.girldevelopit.com/chapters/denver](https://www.girldevelopit.com/chapters/denver)

@Cara-Jo I transferred all of the teacher/bio data over to the Boulder chapter. Mind doing a sanity check on your page for me and giving me the green light if it looks right?

@breethomas you are assigned the Denver chapter and are welcome to add bios, pics, etc. of your team at any time.

**Comment by kstack7** [comment]
woo! thanks for doing the transfer, @juliaelman...

**Comment by juliaelman** [comment]
Got approval from @Cara-Jo and closing this one down! Thanks everyone for your feedback and help :raised_hands:
