### ISSUE TITLE
Move the Donate Link

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#196]
Description
Donate link

Ask
The Donate link shouldn't be the first thing a user sees. 

To Do
Move the donate link to the end of the menu.  

Reword the sentence
Here's the new order: About, Chapters, Materials, Donate

Additional Info
The donate link shouldn't be the first thing a user sees. They need to know about GDI before they are asked to date.

**Comment by juliaelman** [comment]
@staceyturnage not entirely sure we want to move forward with this and move the donate button to the end. Would be good to get some direct examples and/or studies that prove that we *need* to move to the end of the nav links.

@corinnepw what are your thoughts on the importance of where the donate link is in the main nav? I feel like you have the best perspective on how easily people are able to find out that information.

**Comment by staceyturnage** [comment]
Here's are a few nonprofit technology group that has "support" at the end
of their menu!

http://www.nten.org

http://www.techsoup.org

Code.org has their donate button at the bottom of the page

http://code.org

Stacey

On Wed, Feb 11, 2015 at 8:57 PM, Julia Elman <notifications@github.com>
wrote:

> @staceyturnage <https://github.com/staceyturnage> not entirely sure we
> want to move forward with this and move the donate button to the end. Would
> be good to get some direct examples and/or studies that prove that we
> *need* to move to the end of the nav links.
>
> @corinnepw <https://github.com/corinnepw> what are your thoughts on the
> importance of where the donate link is in the main nav? I feel like you
> have the best perspective on how easily people are able to find out that
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girldevelopit/gdi-new-site/issues/196#issuecomment-74009447>
> .
>



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage

**Comment by corinnepw** [comment]
@staceyturnage I think case studies/research from reputable sources on the placement of the donate button versus examples of NPO sites are more informative. See some below.
@juliaelman basically all of the research I've done over the past couple months has been to include it prominently on the main nav and to even make it a different color to help it stand out.
I believe @Cara-Jo may have some thoughts on this as well

The most upvoted answer on this [UX Stack Exchange](http://ux.stackexchange.com/questions/16088/ideal-location-for-a-donate-button) forum has some great info about making the donate button prominent and included in the main nav.
Here's an excerpt: *Donate button is THE element to be featured throughout a non-profit's website. It should be easily visible everywhere. You shouldn't worry about being "too pushy" because donations fuel non-profits.
If you put it into a menu or the footer, you're going to destroy collections because it won't be visible to the majority of visitors.*
I like [this post](http://branded4good.com/doante-button/) because it discusses a bunch of options and shows great examples.

I believe it should remain where it is, and after some user testing down the line, we should figure out whether or not we want to change the color to make it stand out more.

**Comment by staceyturnage** [comment]
It was a simply a suggestion it can remain where it is.

As a potential donor I would want to know about the organization before I
was asked to donate, just my opinion.

Stacey

On Wed, Feb 11, 2015 at 10:40 PM, Corinne <notifications@github.com> wrote:

> @staceyturnage <https://github.com/staceyturnage> I think case
> studies/research from reputable sources on the placement of the donate
> button versus examples of NPO sites are more informative. See some below.
> @juliaelman <https://github.com/juliaelman> basically all of the research
> I've done over the past couple months has been to include it prominently on
> the main nav and to even make it a different color to help it stand out.
> I believe @Cara-Jo <https://github.com/Cara-Jo> may have some thoughts on
> this as well
>
> The most upvoted answer on this UX Stack Exchange
> <http://ux.stackexchange.com/questions/16088/ideal-location-for-a-donate-button>
> forum has some great info about making the donate button prominent and
> included in the main nav.
> Here's an excerpt:
> *Donate button is THE element to be featured throughout a non-profit's
> website. It should be easily visible everywhere. You shouldn't worry about
> being "too pushy" because donations fuel non-profits. If you put it into a
> menu or the footer, you're going to destroy collections because it won't be
> visible to the majority of visitors.*
> I like this post <http://branded4good.com/doante-button/> because it
> discusses a bunch of options and shows great examples.
>
> I believe it should remain where it is, and after some user testing down
> the line, we should figure out whether or not we want to change the color
> to make it stand out more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girldevelopit/gdi-new-site/issues/196#issuecomment-74016716>
> .
>



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage

**Comment by kstack7** [comment]
This makes for a good discussion, @staceyturnage, and I'm glad you brought it up. It's good that we're all posting examples to help decide this direction. I checked out other organizations similar to ours and noticed a pattern in very loud DONATE buttons, which can be fitting for groups that aren't backed by giant companies or even the government.

Let's get through launch and keep tabs on immediate feedback and maybe we'll have a good idea of what does and doesn't work in the near future :+1: 

Thanks, lady!

**Comment by staceyturnage** [comment]
I'm not asking for it to be removed from the page I'm simply asking can it
be repositioned. I have no problem with it being prominently displayed but
the first thing a potential donor sees I don't know if that's a good thing.

As I mentioned before I'm coming from a user's prospective and what better
way to see that is to look @ other nonprofit's websites (end result of the
development process).

Or here's a thought maybe it shouldn't say "donate" maybe it should say
"support us" but again whatever is decided is fine with me.

Stacey



On Wed, Feb 11, 2015 at 10:43 PM, Stacey Turnage <stacey@girldevelopit.com>
wrote:

> It was a simply a suggestion it can remain where it is.
>
> As a potential donor I would want to know about the organization before I
> was asked to donate, just my opinion.
>
> Stacey
>
> On Wed, Feb 11, 2015 at 10:40 PM, Corinne <notifications@github.com>
> wrote:
>
>> @staceyturnage <https://github.com/staceyturnage> I think case
>> studies/research from reputable sources on the placement of the donate
>> button versus examples of NPO sites are more informative. See some below.
>> @juliaelman <https://github.com/juliaelman> basically all of the
>> research I've done over the past couple months has been to include it
>> prominently on the main nav and to even make it a different color to help
>> it stand out.
>> I believe @Cara-Jo <https://github.com/Cara-Jo> may have some thoughts
>> on this as well
>>
>> The most upvoted answer on this UX Stack Exchange
>> <http://ux.stackexchange.com/questions/16088/ideal-location-for-a-donate-button>
>> forum has some great info about making the donate button prominent and
>> included in the main nav.
>> Here's an excerpt:
>> *Donate button is THE element to be featured throughout a non-profit's
>> website. It should be easily visible everywhere. You shouldn't worry about
>> being "too pushy" because donations fuel non-profits. If you put it into a
>> menu or the footer, you're going to destroy collections because it won't be
>> visible to the majority of visitors.*
>> I like this post <http://branded4good.com/doante-button/> because it
>> discusses a bunch of options and shows great examples.
>>
>> I believe it should remain where it is, and after some user testing down
>> the line, we should figure out whether or not we want to change the color
>> to make it stand out more.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/girldevelopit/gdi-new-site/issues/196#issuecomment-74016716>
>> .
>>
>
>
>
> --
> STACEY TURNAGE | Founder | Girl Develop It Houston |
> stacey@girldevelopit.com | girldevelopit.com | Houston Meetup |
> @gdihouston | @staceyyturnage
>



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage

**Comment by staceyturnage** [comment]
---------- Forwarded message ----------
From: Stacey Turnage <stacey@girldevelopit.com>
Date: Wed, Feb 11, 2015 at 10:50 PM
Subject: Re: [gdi-new-site] Move the Donate Link (#196)
To: girldevelopit/gdi-new-site <
reply@reply.github.com
>


I'm not asking for it to be removed from the page I'm simply asking can it
be repositioned. I have no problem with it being prominently displayed but
the first thing a potential donor sees I don't know if that's a good thing.

As I mentioned before I'm coming from a user's prospective and what better
way to see that is to look @ other nonprofit's websites (end result of the
development process).

Or here's a thought maybe it shouldn't say "donate" maybe it should say
"support us" but again whatever is decided is fine with me.

Stacey



On Wed, Feb 11, 2015 at 10:43 PM, Stacey Turnage <stacey@girldevelopit.com>
wrote:

> It was a simply a suggestion it can remain where it is.
>
> As a potential donor I would want to know about the organization before I
> was asked to donate, just my opinion.
>
> Stacey
>
> On Wed, Feb 11, 2015 at 10:40 PM, Corinne <notifications@github.com>
> wrote:
>
>> @staceyturnage <https://github.com/staceyturnage> I think case
>> studies/research from reputable sources on the placement of the donate
>> button versus examples of NPO sites are more informative. See some below.
>> @juliaelman <https://github.com/juliaelman> basically all of the
>> research I've done over the past couple months has been to include it
>> prominently on the main nav and to even make it a different color to help
>> it stand out.
>> I believe @Cara-Jo <https://github.com/Cara-Jo> may have some thoughts
>> on this as well
>>
>> The most upvoted answer on this UX Stack Exchange
>> <http://ux.stackexchange.com/questions/16088/ideal-location-for-a-donate-button>
>> forum has some great info about making the donate button prominent and
>> included in the main nav.
>> Here's an excerpt:
>> *Donate button is THE element to be featured throughout a non-profit's
>> website. It should be easily visible everywhere. You shouldn't worry about
>> being "too pushy" because donations fuel non-profits. If you put it into a
>> menu or the footer, you're going to destroy collections because it won't be
>> visible to the majority of visitors.*
>> I like this post <http://branded4good.com/doante-button/> because it
>> discusses a bunch of options and shows great examples.
>>
>> I believe it should remain where it is, and after some user testing down
>> the line, we should figure out whether or not we want to change the color
>> to make it stand out more.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/girldevelopit/gdi-new-site/issues/196#issuecomment-74016716>
>> .
>>
>
>
>
> --
> STACEY TURNAGE | Founder | Girl Develop It Houston |
> stacey@girldevelopit.com | girldevelopit.com | Houston Meetup |
> @gdihouston | @staceyyturnage
>



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage



-- 
STACEY TURNAGE | Founder | Girl Develop It Houston |
stacey@girldevelopit.com | girldevelopit.com | Houston Meetup | @gdihouston
| @staceyyturnage

**Comment by juliaelman** [comment]
@staceyturnage thank you for your thoughtful feedback and for initially posting this issue! While I see your point of view as the user, I also see @corinnepw point and the articles of evidence she provided to support this decision.

I am going to close this issue, but the website team will definitely keep their ears to the ground to hear what our users think post launch. It might help putting specific analytics on the button to see how many click throughs we get when the link is in one place vs. the other? We could use something like [Optimizely](https://www.optimizely.com/) to do the testing! \o/ But then... that would be on another issue.

@staceyturnage thank you again for your continued insight and feedback on this project! It is very much appreciated!!!!
