### ISSUE TITLE
San Diego Chapter not listed on the main site

### ISSUE THREAD

**Issue by jwala1506** [girldevelopit/gdi-new-site#201]
Meetup URL: http://www.meetup.com/Girl-Develop-It-San-Diego/
Twitter: https://twitter.com/GDISD
Facebook: https://www.facebook.com/GDIInSD

[Please remove April from Chapter Leader. She left GDI last year.]
Chapter Leader:
Full Name: Jyoti Wadhwani
GDI email address: jyoti@girldevelopit.com
Twitter: @wadhwanijyoti
Github: jwala1506

Bio: She is passionate about technology and wants to bring more women closer to money through tech. She received her Masters degree from UC San Diego in Computer Engineering and has been working in Qualcomm as a Software Engineer since then. At Qualcomm she develops secure kernel drivers for Mobile Operating Systems. For few months at UC San Diego, she taught small kids Scratch programming language and she loved the experience. As the next step to pursue her passion in teaching, she wants to teach coding skills to women from diverse backgrounds. At Girl Develop It she wants to combat all stereotype threats that women face by disproving them. Other than teaching and coding, she enjoys hiking and swimming.

**Comment by juliaelman** [comment]
@jwala1506 I've updated you page with the above request: https://girl-develop-it.herokuapp.com/chapters/san-diego Please verify that the changes have been made and everything looks good! :+1:

**Comment by jwala1506** [comment]
Hey! the website looks good. thank you @juliaelman :+1:

**Comment by Roenok** [comment]
Approved and closed.
