### ISSUE TITLE
Enhancement: Provide a way to sort curriculum

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#202]
**Description**
Currently, the classes on the curriculum page are sorted by enter date (I believe). We need a way to manually sort them.

**Ask**
Add a method to sort classes in the Active Admin interface. This could be a numerical sort-order field, a drag-and-drop, or whatever else the tool allows. 

**To Do**
- [x]  Investigate possible sorting methods
- [x] Add appropriate fields to DB
- [x] Add to active admin

**Additional Info**
Can happen post-launch. I think some users might find a similar system handy for instructors/volunteers on their chapter pages.

**Comment by kstack7** [comment]
Coming up in PR #288

**Comment by kstack7** [comment]
Now available on staging! Have at it!

https://girl-develop-it-staging.herokuapp.com

**Comment by kstack7** [comment]
NOTE: DB changes are on a staging db. So just check it out for functionality and layout without putting tons of time into it haha the live db will need the real changes :)

**Comment by kstack7** [comment]
Closed with #288
