### ISSUE TITLE
Chapter names and Admin names are not parsing correctly in the admin.

### ISSUE THREAD

**Issue by Cara-Jo** [girldevelopit/gdi-new-site#203]
**Description** 
When navigating to the bios section of the admin page, the names are displayed wrong. They should be displayed with human readable names like "Boulder, Philadelphia" for the chapter names or "Cara Jo, Kristen" for the admin names.

 **Ask** 
Please fix this so we can sort through all the bios! Many people! 

 **To Do** 
 - [ ] Fix Admin name display
 - [ ] Fix Chapter Name Display 
 - [ ] Celebrate

 **Additional Info** 
Here's a screenshot of the culprit.
![screenshot 2015-02-11 10 52 57](https://cloud.githubusercontent.com/assets/180763/6154776/88c7afae-b1eb-11e4-83e2-3d0d753dbf9d.png)

**Comment by kstack7** [comment]
I have to double-check the db relationships to see if I can easily pull all the admin names, but I can definitely snag the chapters for now...this looking better? 

![screen shot 2015-02-12 at 1 01 45 am](https://cloud.githubusercontent.com/assets/6612770/6162534/dd34e9c8-b252-11e4-96da-28af007c0d0d.png)
