### ISSUE TITLE
Update link color to increase contrast and legibility 

### ISSUE THREAD

**Issue by Cara-Jo** [girldevelopit/gdi-new-site#204]
**Description** 

I care about the usability of the website and find the 'gold' links hard to read. Especially for the users who do not have 20/20 vision. 

They should also be underlined so that users know they are a link.

 **Ask** 
Let's change the links to either the standard blue or green! I'm open to discussion about this - but think the links should be blue. 

Of course these colors will be GDI flavored.

 **To Do** 

 - [x] Discuss a new color
 - [ ] Make links that color and add a sweet underline.

**Comment by Roenok** [comment]
I vote blue, for maximum color blind friendliness. Also, we want to shoot for a 3:1 contrast ratio with our regular text color, if possible, per WCAG 2.0 guidelines

http://www.w3.org/TR/WCAG20-TECHS/G183.html

**Comment by juliaelman** [comment]
:+1: on blue! #0066CC?

**Comment by Cara-Jo** [comment]
Our brand blue is #00A9B4 Not sure if that matters at all or if it's high enough contrast. 

See brandfolder.com/gdi

**Comment by juliaelman** [comment]
@Cara-Jo sticking with the brand sounds good to me! 

@Roenok suggestions on the contrast?

**Comment by Roenok** [comment]
Brand blue is too light; it has a 2.9:1 contrast ratio with white, which isn't much better than the gold. If we go a touch darker, #00838C has a 4.5:1 ratio with white and a 3:1 ratio with our default text color, making it a perfect match with WCAG 2.0 guidelines

**Comment by Cara-Jo** [comment]
I’m good with that! #00838C it is! 
-- 
CARA JO MILLER | Co-founder | Girl Develop It Boulder/Denver | 248.230.0910 | carajo@girldevelopit.com | girldevelopit.com | @GDIboulder | @GDIDenver | @corrinajo

On February 16, 2015 at 7:16:21 PM, Sylvia Richardson (notifications@github.com) wrote:

Brand blue is too light; it has a 2.9:1 contrast ratio with white, which isn't much better than the gold. If we go a touch darker, #00838C has a 4.5:1 ratio with white and a 3:1 ratio with our default text color, making it a perfect match with WCAG 2.0 guidelines
