### ISSUE TITLE
Make icons for all the classes listed on Materials page

### ISSUE THREAD

**Issue by Cara-Jo** [girldevelopit/gdi-new-site#208]
**Description** 
Make icons for each class listed on the materials page so that they are consistent across the page.

 **Ask** 
Create .png files that are 512x512 pixels with a navy blue icon that represents that class.

 **To Do** 

- [ ] Make the icons
- [ ] Load them into images/materials so that they are accesable by all.
- [ ] Include source file in .ai or .pdf format  

**Additional Info** 
Example HTML icon
![html](https://cloud.githubusercontent.com/assets/180763/6173796/c9dafcbe-b2a7-11e4-87a7-f6214c800b0a.png)

**Comment by Cara-Jo** [comment]
I've started on this as apart of #193

**Comment by kstack7** [comment]
:+1: nice!

**Comment by kstack7** [comment]
Yes!

**Comment by kstack7** [comment]
Wait...are we missing a few here? I'll leave for post-launch if more time is needed. We do have place-holders on the site for nwo

**Comment by Roenok** [comment]
@Cara-Jo You can email the files when you have them ready, and I'll drop them in via the admin. Thanks!

**Comment by Cara-Jo** [comment]
Will do @Roenok. Sorry @kstack7 I didn't upload them with the PR.

**Comment by kstack7** [comment]
No big! Easy fix, @Cara-Jo :)

**Comment by heiwanalady** [comment]
Hi! Is this issue still open?

**Comment by Roenok** [comment]
We currently have icons for everything (thanks @Cara-Jo), so closing this old issue.
