### ISSUE TITLE
Add skip navigation link, for accessibility

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#210]
**Description**
Right now, keyboard and screen reader users need to tab through the entire navigation menu to get to the content. We want to provide a way to skip the navigation menu.

**Ask**
Add a hidden anchor link that skips to the main content. This link should appear on focus. Some suggested code below.

**To Do**
- [x] Add anchor link to header file, right below opening body tag
- [x] Add corresponding ID and tabindex="-1" to main content section
- [x] Add some CSS to make it beautiful
- [x] Test new link
- [x] Celebrate our increased accessibility

**Additional Info**
Can happen post-launch. Suggested code below, but feel free to adjust.

```
<!-- Add below body tag-->
<a id="skipnav" href="#maincontent">Skip to main content</a>

<!-- Update main section -->
<section class="main-container" id="maincontent" tabindex="-1">

<!-- CSS it up -->
a#skipnav {
	padding:6px;
	position: absolute;
	top:-40px;
	left:0px;
	color:#da141e;
	background:transparent;
	-webkit-transition: top 1s ease-out, background 1s linear;
    transition: top 1s ease-out, background 1s linear;
    z-index: 100;
}

a#skipnav:focus {
	position:absolute;
	left:0px;
	top:0px;
	background:white;
	outline:0;	
	-webkit-transition: top .1s ease-in, background .5s linear;
	transition: top .1s ease-in, background .5s linear;
}

section#maincontent {
	outline:0;
}

```

**Comment by juliaelman** [comment]
I got this one!
