### ISSUE TITLE
Create custom 404 page

### ISSUE THREAD

**Issue by minamarkham** [girldevelopit/gdi-new-site#214]
**Description**
There is currently a generic 404 page appearing on the site. I think the a branded 404 page to match the rest of the site is a better experience for users, and is more engaging.

**Ask**
Create new custom 404 error page to match new branding.

**To Do**
- [x] Write content for the page
- [x] Create design/layout
- [x] Create route exceptions
- [x] Add new template and styling

**Additional Info**
![Curent 404](https://cloud.githubusercontent.com/assets/876210/6181774/b9e238da-b2fd-11e4-9ebc-d4f75bded7e5.png)

**Comment by Roenok** [comment]
Awesome idea, @minamarkham!

**Comment by minamarkham** [comment]
Coded something up real quick. What do we think?

![Error page](https://cloud.githubusercontent.com/assets/876210/6182954/866e4ae6-b313-11e4-8b90-bfc9ec3d9a60.png)

**Comment by juliaelman** [comment]
Love it @minamarkham!

**Comment by juliaelman** [comment]
Fixed #220
