### ISSUE TITLE
Fix margins on the "our story" section of /about

### ISSUE THREAD

**Issue by minamarkham** [girldevelopit/gdi-new-site#215]
**Description**
The "our story" section of the about page currently runs into the text surrounding it.

**Ask**
Add margins to the "our story" section.

**Additional Info**
![Fix it :)](https://cloud.githubusercontent.com/assets/876210/6181848/44582672-b2ff-11e4-8c74-16f8e1779f08.png)

**Comment by kstack7** [comment]
Yeah would be really helpful to isolate the .support{} class to the donation page, as that is why this spacing got wacked...

**Comment by kstack7** [comment]
@minamarkham are you taking this or just setting the issue? I can tackle if you'd like

**Comment by minamarkham** [comment]
I can do it.

**Comment by kstack7** [comment]
Okay! Didn't wanna overlap if you were on it :+1:

**Comment by juliaelman** [comment]
@minamarkham I am going to re-assign this to @kstack7, as we need to get this wrapped up before launch! thanks for offering to help <3

**Comment by kstack7** [comment]
Better, right?

![screen shot 2015-02-12 at 11 58 12 pm](https://cloud.githubusercontent.com/assets/6612770/6182507/293642fc-b313-11e4-8161-5e405bb57230.png)

**Comment by juliaelman** [comment]
@kstack7 much! :sparkler:

**Comment by juliaelman** [comment]
Fixed #216.
