### ISSUE TITLE
Provide some way to reorder instructors/volunteers lists on chapter pages

### ISSUE THREAD

**Issue by mmcelaney** [girldevelopit/gdi-new-site#217]
Description
I've got one male volunteer who is defaulting to the top of the list and I don't know how to get his bio moved down a bit! Just seems weird, is all. Screenshot of what I mean: http://grab.by/ELaW

Ask
Can functionality be added in the heroku app to reorder the volunteers and/or instructors on the chapters page? I'm not equipped to offer the best/right way to do this!

To Do
I am not the right person to offer the best/right solution, so I need help on how we can accomplish this task! Halp! :) <3

**Comment by juliaelman** [comment]
@mmcelaney thanks for the issue! Would you mind re-formatting it to fit this template in #83?

**Comment by mmcelaney** [comment]
Thanks @juliaelman! reformatting it now...

**Comment by kstack7** [comment]
I think we'll need a "rank" or "position" type of field in the database for the areas needing this type of sort. @DBNess (or any other db'ers) what do you think?

**Comment by Roenok** [comment]
Linking this one to https://github.com/girldevelopit/gdi-new-site/issues/202; whatever solution works here should work for classes too.

**Comment by beckysingson** [comment]
+1 priority on this one, pls & thank you lovelies

**Comment by kstack7** [comment]
Coming up in PR #288

**Comment by kstack7** [comment]
Sorting capabilities are available on our 'staging' site. Try 'em out!

https://girl-develop-it-staging.herokuapp.com

**Comment by kstack7** [comment]
NOTE: Testing on staging site will only change the staging db. So just check it out for functionality and layout without putting tons of time into it haha the live db will need the real sorting changes :)

**Comment by kstack7** [comment]
Closed with #288
