### ISSUE TITLE
Change out all `http` references to `https`

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#218]
**Description**
*Currently, we have added SSL to the website and need to swap out our http requests around the site to https.*

**Ask**
*Swap out all `http` requests for `https` requests instead.*

**To Do**
- [x] View all places where `http` references live > [https://github.com/girldevelopit/gdi-new-site/search?utf8=%E2%9C%93&q=http](https://github.com/girldevelopit/gdi-new-site/search?utf8=%E2%9C%93&q=http)
- [x] Replace with `https` and/or a bare domain (which will default to https)

**Comment by kstack7** [comment]
Will have done by official launch :+1:

**Comment by juliaelman** [comment]
Looks good! :+1: Making note of our discussion on creating relative paths to links, as opposed to absolute, in the future.
