### ISSUE TITLE
Update About page bios

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-new-site#219]
1. Update Corinne's bio to:
Corinne is a passionate advocate for community-centered movements and their power to change the world. She is the Executive Director of Girl Develop It. For two years prior to becoming the first ED of Girl Develop It, she co-lead the organization’s Philadelphia chapter to become one of the largest and most active.<br>Previously she worked with the [Technical.ly](http://technical.ly) news network producing large-scale technology conferences like [Philly Tech Week](http://phillytechweek.com) and Baltimore Innovation Week. In that role, Corinne promoted diversity initiatives and helped build relationships among the respective local tech communities of Philadelphia, Baltimore and Brooklyn.<br> A native Californian, Corinne moved to Philadelphia after studying Sociology and Film & Digital Media at University of California – Santa Cruz, and worked in the newsroom and in community relations at [WHYY](http://whyy.org), Philadelphia’s NPR and PBS affiliate for two years thereafter. Corinne has also written freelance for various publications and is active on the Board of Directors for the [Prometheus Radio Project](http://www.prometheusradio.org).

2. Change the "//" between Vanessa's name and title to be a comma "," and add "Advisor" to title after Co-Founder

**Comment by corinnepw** [comment]
@DBNess any updates needed for your bio?

**Comment by juliaelman** [comment]
Fixed with #227
