### ISSUE TITLE
Header navigation hover state overflows the header

### ISSUE THREAD

**Issue by nahurst** [girldevelopit/gdi-new-site#221]
The black hover state you see when hovering over header navigation links is bigger than the header. This happens on the latest Chrome and Firefox on OS X.
![header-hover](https://cloud.githubusercontent.com/assets/270532/6196892/8782809e-b3ab-11e4-984d-a92a7fe47acb.png)

**Comment by juliaelman** [comment]
@nahurst thanks for pointing this out! I believe this is an intentional design decision by the original creator, hence the drop-shadow effect around the button.

@minamarkham @Cara-Jo thoughts on this? Is this something we want to change?

**Comment by kstack7** [comment]
I also thought this was intentional

**Comment by minamarkham** [comment]
Pretty sure it's intentional, but just in case, here's what it looks like "fixed":

![Hover](https://cloud.githubusercontent.com/assets/876210/6197011/8d7a585c-b3a4-11e4-8d55-6c704f22bc29.png)

**Comment by Cara-Jo** [comment]
It is an intentional design decision. H0wever, the drop shadow is not consistent with any other branding guidelines that we have in place. So I'm up for removing the drop shadow, but I kind of like the tab look.

**Comment by juliaelman** [comment]
@Cara-Jo cool! Thank you for your feedback :dancer: 

@nahurst thoughts?

**Comment by nahurst** [comment]
I like the newer/aligned version.

**Comment by kstack7** [comment]
Is that new example totally aligned? Seems a pixel off still...

**Comment by minamarkham** [comment]
I think it is. It was a quick and dirty in the browser mockup.

**Comment by kstack7** [comment]
OH okay! That's fair just hoping that was seen by all haha

I feel like I can't unsee the tabs now though! Aligned seems too plain...

**Comment by kstack7** [comment]
Where do we stand with this? Love/hate the tab look? Let's finalize or close this :)

**Comment by therufs** [comment]
Is there a place we can see the tab version w/o the drop shadow?

**Comment by kstack7** [comment]
I think the best option is to use DevTools (I prefer Chrome) to disable the CSS

@ media screen and (min-width: 500px)
header nav a:hover {
  background-color: #282828;
  color: #fbcfc6;
  /\* box-shadow: 0.025rem 0.025rem 0.5rem #282828; */
}

This is the result when hovering and active:

![screen shot 2015-05-03 at 11 09 06 pm](https://cloud.githubusercontent.com/assets/6612770/7448503/ac81f9fc-f1e9-11e4-8837-385e56397a24.png)

**Comment by kstack7** [comment]
^ woops haha put a space between @ and media to not activate the tag

**Comment by DBNess** [comment]
:+1: to removing the drop shadow! thanks @kstack7. I could take or leave the oversized tabs - I agree with @nahurst that they looked a bit like a bug before, but they look cleaner without the drop shadow so I'd be okay leaving them if @Cara-Jo & others would like to, or I'd be down for a slimmed version like what @minamarkham proposed.

tl:dr; win-win-win but drop the drop shadow?

**Comment by kstack7** [comment]
Yeah I think what kept them from looking like a bug to me is the fact the text centered when hovered/active. Otherwise I think it'd look way off. I'm down with dropping the shadow and leaving the rest as it is :+1:

**Comment by therufs** [comment]
I feel like it looks a little less polished without the shadow, but agree it doesn't go with anything else. Herm. 

Either way, another :+1: for tabs :)

**Comment by kstack7** [comment]
Shadows-be-gone: https://girl-develop-it-staging.herokuapp.com/

**Comment by DBNess** [comment]
\o/!

On Wednesday, May 13, 2015, Kristen notifications@github.com wrote:

> Shadows-be-gone: https://girl-develop-it-staging.herokuapp.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-new-site/issues/221#issuecomment-101515365
> .

## 

Vanessa Hurst
Co-Founder | Girl Develop It http://www.girldevelopit.com | @girldevelopit
http://twitter.com/girldevelopit

Girl Develop It http://girldevelopit.com/ teaches women to code in over
45 cities
CodeMontage http://www.codemontage.com/ empowers coders to change the
world
Women coders break new ground, and stereotypes - TODAY show
http://www.today.com/video/today/53924117
