### ISSUE TITLE
Email links broken on /sponsors

### ISSUE THREAD

**Issue by minamarkham** [girldevelopit/gdi-new-site#222]
**Description**
Email links on the sponsor page go to a 404.

**Ask**
Change links to mailto links.

**Comment by minamarkham** [comment]
Fixing now cause it's my fault :(

**Comment by juliaelman** [comment]
@minamarkham this is not just your fault! It's mine too for not catching during the PR.

**Comment by juliaelman** [comment]
Had to do some finagling in order to fix some commit history issues, but the commit is in there now! :dancer:
