### ISSUE TITLE
On Materials page make the whole area of .material-container to be clickable

### ISSUE THREAD

**Issue by gorork** [girldevelopit/gdi-new-site#224]
**Description**
Currently **.material-container** section is being highlighted on hover (check the screenshot below).
However, users can click only on its title and icon, which are not being changed on hover. This might feel a bit confusing for users.

![screen shot 2015-02-12 at 20 06 50](https://cloud.githubusercontent.com/assets/6679057/6182135/ce6acd9a-b2f2-11e4-906d-589458963f06.png)

**Ask**
Making the whole section clickable will keep the style and UX in consistence and easy-to-use.

**To Do**
- [ ] make **.material-container** section clickable

**Comment by juliaelman** [comment]
Thank you for submitting this issue @gorork! Would you mind re-formatting your issue in the following templated format? #83

**Comment by gorork** [comment]
@juliaelman Done!

**Comment by juliaelman** [comment]
@gorork thank you!

**Comment by gorork** [comment]
@juliaelman I'd take care of it, but I don't have environment installed yet ;)
