### ISSUE TITLE
Animate.css getting lost

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-new-site#232]
**Description**
*The animate.css is throwing a GET error while we only have an animate.css.scss in assets*

**Ask**
*To either link the animate.css.scss or include an animate.css file as needed*

**To Do**
- [x] Understand which file is actually needed for our code/designs
- [x] Link the proper file to squish the GET error

**Additional Info**
![screen shot 2015-02-14 at 1 22 59 am](https://cloud.githubusercontent.com/assets/6612770/6198812/74486d4e-b3e8-11e4-9394-627f6a050108.png)

**Comment by kstack7** [comment]
Any designers/CSS'ers want to take a stab at this? I'm not sure if the animate.css is even necessary. Would love additional design input.

**Comment by amygori** [comment]
Animate.css is only being used for the homepage animation -- at least, it was originally. We initially installed the whole library as we considering options for the opening animations, but it's definitely overkill as we are only using one animation. Seems like a good time to bid it farewell it if it's throwing errors. I'll take a look.

**Comment by kstack7** [comment]
Thanks Amy! I since pushed a PR #255 to get rid of it. You can review that or I can close it if you think we should put it back. Note that animate.css.scss is still there (I think the .css version was meant to be deleted but wasn't).

**Comment by danlucas** [comment]
A quick question: how would one test this?  The error (for me at least) only shows up on the production site but running the site locally in production mode doesn't produce the error.  So while I'm pretty sure @kstack7's PR will fix the error is there anyway to know that before it gets pushed to production?
