### ISSUE TITLE
Do not display closed/sold out classes on chapter page

### ISSUE THREAD

**Issue by beckysingson** [girldevelopit/gdi-new-site#233]
**Description**
Closed & sold out classes currently appear in the available class list at top of Chapter Page template. 

**Ask**
Not sure if the Meetup API has the appropriate endpoint but it would be awesome if closed or sold out classes did not appear on available classes list on the chapter pages. For example, our page currently displays a Wordpress workshop that is already sold out (meanwhile we have 3 other classes open that don't yet show up on our top 3 on the chapter page). 

**To Do**
* [ ] Confirm if Meetup API supports an endpoint that informs whether a class is closed/sold out
* [ ] Modify chapter pg template to no longer display classes that are not available for registration

*Additional Info*
For example, see https://www.girldevelopit.com/chapters/cincinnati -- this class is currently sold out thus would prefer that it not be displayed http://www.meetup.com/Girl-Develop-It-Cincinnati/events/218895024/

**Comment by juliaelman** [comment]
@beckysingson thanks for adding your issue! Would you mind re-formatting it to follow the structure on #83?

**Comment by beckysingson** [comment]
@juliaelman you got it, dude

**Comment by Roenok** [comment]
Personal thought: It's not uncommon for all of our upcoming classes and events to be sold out. I would prefer to have them there, so it doesn't look like we are not posting anything. Plus, sold-out events can be a draw for people to sign up for the Meetup to hear about the next one. 

What do y'all think of some find of full or sold out marker?

**Comment by minamarkham** [comment]
I'd prefer a full/sold out indicator, for all the reasons @Roenok said.

**Comment by Roenok** [comment]
30-second mockups:
![option1](https://cloud.githubusercontent.com/assets/925963/6220351/4f9e8240-b603-11e4-8649-939d9ac466db.png)
![option2](https://cloud.githubusercontent.com/assets/925963/6220350/4f9c5736-b603-11e4-80b7-73bf35136882.png)

Other ideas, team? (especially @Cara-Jo)

**Comment by kstack7** [comment]
I like the blatant " - SOLD OUT" as it's anchored a bit more than the corner ribbon...that may look funky while free-floating in a list with white space. Also thinking we can nix the map at that point so that a sold out course doesn't take as much real estate...make sense?

**Comment by minamarkham** [comment]
Like this?

![screen shot 2015-02-16 at 5 04 31 pm](https://cloud.githubusercontent.com/assets/876210/6220609/eb53aa4a-b5fd-11e4-981f-6417762571fd.png)

**Comment by kstack7** [comment]
Yea that's decent! We want folks to see what they could maybe catch next
time around, but not take away the spotlight for available courses. I like
it :)

**Comment by minamarkham** [comment]
If it's sold out, maybe we should nix the "RSVP" button too? Or at least change the text.

**Comment by kstack7** [comment]
Oh yeah definitely...probably nix it for now...

**Comment by Roenok** [comment]
Maybe change RSVP to Details or similar? It's still valuable as information. 

Re: the map, there are some plans in the works to redesign as side-by-side/new button:
https://github.com/girldevelopit/gdi-new-site/issues/187

I'd leave the map in so it does not disrupt that layout.

**Comment by minamarkham** [comment]
Okay. How about this?

![screen shot 2015-02-16 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/876210/6220858/1d34a3c2-b601-11e4-9b14-d52ca49c664c.png)

**Comment by beckysingson** [comment]
Love all of this thinking. Thanks @kstack7 @Roenok @minamarkham 
+1 -- I dig what you've done there @minamarkham 

To add further to my original rationale for this request - I don't like that I can only see the three upcoming classes, despite them being sold out yet I have three open classes thereafter that are not yet sold out that I would rather promote over those that are sold out. So perhaps a future feature request to be able to either curate which classes from my Meetup feed do/do not show up (or be able to sticky certain classes as the case may be) or increase the number of classes that are displayed at a time (e.g. more than 3, or show all, or show 5, and/or modify display to a list view in situations where more than 3 classes are open, etc). Let me know if y'all have any thoughts there.

**Comment by kstack7** [comment]
Ahhh good, good points. Seems like the logical transition would be to focus on a set timeframe vs. a course count. Say we grab classes up to 2 months out and display the open ones first with RSVP and the "sold out" with a ribbon and "details" button...

**Comment by kstack7** [comment]
OR we let the API iterate until it has 3 open courses and can put the rest of whatever status in a different spot on the page.

**Comment by kstack7** [comment]
@staceyturnage brought up the idea of showing past courses as well. I figured we can all talk this out here while we decide what to do about the "sold out" courses. :+1:

**Comment by minamarkham** [comment]
Hmmm. Meetup has a "featured meetup" feature. (Wow, that's a tongue twister). Could we utilize that to display some classes above others?

**Comment by kstack7** [comment]
oo yeah we can use that to always display the featured meetup at the top.

**Comment by minamarkham** [comment]
@kstack7 can you assign this to me please?

**Comment by kstack7** [comment]
Woops got click happy...done and done, @minamarkham :)

**Comment by minamarkham** [comment]
Okay, 'tis done!
What do we think?

![screen shot 2015-05-13 at 12 51 29 pm](https://cloud.githubusercontent.com/assets/876210/7618059/14c0b9a8-f975-11e4-9e80-b07989385176.png)

![screen shot 2015-05-13 at 12 51 39 pm](https://cloud.githubusercontent.com/assets/876210/7618062/19284cd6-f975-11e4-89f8-b6eaf703844b.png)

**Comment by kstack7** [comment]
this is up on staging if anyone wants to see it in action:

https://girl-develop-it-staging.herokuapp.com/chapters/philadelphia
https://girl-develop-it-staging.herokuapp.com/chapters/austin

thanks @minamarkham!
