### ISSUE TITLE
Footer doesn't reach bottom of page on mobile

### ISSUE THREAD

**Issue by rahobbs** [girldevelopit/gdi-new-site#238]
**Description**
On a 1st gen Moto X in Chrome. When viewing the site in portrait, the footer doesn't reach the bottom of the page.

**Ask**
Make the footer align with the bottom of the page

**Additional Info**
![screenshot_2015-02-16-10-24-54](https://cloud.githubusercontent.com/assets/579715/6214707/89e809d4-b5c8-11e4-8057-d554dda58ec1.png)

**Comment by juliaelman** [comment]
@rahobbs hihihihihi! Thanks for posting this issue! Would you mind reformatting into something like the following template #83. 

Hope all is well with you! <3
