### ISSUE TITLE
Nav links overflow onto light background on mobile

### ISSUE THREAD

**Issue by rahobbs** [girldevelopit/gdi-new-site#239]
**Description**
On a 1st gen Moto X in Chrome. When viewing the site in landscape, the white nav links overflow onto the light background.

**Ask**
In landscape, links should remain on the pink background.

**Additional Info**
![screenshot_2015-02-16-10-25-05](https://cloud.githubusercontent.com/assets/579715/6214738/cab823a4-b5c8-11e4-9bdd-27f35d802f76.png)

**Comment by juliaelman** [comment]
@rahobbs hi again! Would you mind re-formatting this issue to use the following template on #83?

**Comment by rahobbs** [comment]
Re-formatted, sorry that I missed the template before :)

**Comment by juliaelman** [comment]
@rahobbs no worries! We need to help make that more apparent to new contributors somehow... :\

**Comment by artygyrl** [comment]
@rahobbs, I'm going to try to help with this issue
