### ISSUE TITLE
non-retina favicon on site

### ISSUE THREAD

**Issue by charliepark** [girldevelopit/gdi-new-site#241]
**Description**
The favicon (see below) is currently only using a 16px x 16px graphic, which means it looks pixelated on retina screens.
![screen shot 2015-02-16 at 12 52 33 pm](https://cloud.githubusercontent.com/assets/22547/6219150/cdf34140-b5da-11e4-8d5e-151fe8d89dfc.png)

**Ask**
It would be great if the favicon was crisp and retina-ready. [This writeup by Jon Gruber](http://daringfireball.net/2013/01/retina_favicons) is good, but I've done this before for other sites, and would be happy to do one here. I would just need a 48px x 48px (or larger) .png version of the G with the flourish.

**To Do**
- [x] post an asset you'd like turned into the favicon in this thread and I'll get it made and will post a PR.
- [x] if an asset isn't available, I can make one; would just want to know what font to use for that "G"

**Additional Info**
Nothing else! Love the new site!

**Comment by Roenok** [comment]
@charliepark If you don't mind taking this on, assets, fonts, and colors are all in our brand folder:

https://brandfolder.com/gdi

Specifically, wordmark.ai should have everything you need.

**Comment by charliepark** [comment]
Excellent, thank you.

**Comment by charliepark** [comment]
Okay, so here's what I've got at the moment. 
Current on left, new one on right.
![screen shot 2015-02-16 at 8 50 15 pm](https://cloud.githubusercontent.com/assets/22547/6223418/a600aa18-b61d-11e4-9060-cbf1982e1592.png)

Does this work? If so, let me know and I'll fork and submit a PR. If you have any tweaks / suggestions, just let me know. I wasn't sure if the flourish should have greater prominence than it does in the one on the right, but, obviously, that'd make the G a little smaller. But I can change it in any ways you'd like.

* * *

Actually, I figured I'd just make a bunch of alternates and include them here:

![gdi](https://cloud.githubusercontent.com/assets/22547/6223486/55826fca-b61f-11e4-887f-6c8b0d0b709c.png)
![gdi2](https://cloud.githubusercontent.com/assets/22547/6223488/5bb8b318-b61f-11e4-86b6-306864c7dcd3.png)
![gdi3](https://cloud.githubusercontent.com/assets/22547/6223489/5d61d8ca-b61f-11e4-8518-fbf8b317891d.png)
![gdi4](https://cloud.githubusercontent.com/assets/22547/6223491/5eebf144-b61f-11e4-8969-94d6ac64da0f.png)
![gdi5](https://cloud.githubusercontent.com/assets/22547/6223492/62e30896-b61f-11e4-97e9-cb6f943544ad.png)
![gdi6](https://cloud.githubusercontent.com/assets/22547/6223494/6451427e-b61f-11e4-9e7d-13f3ca21b103.png)
![gdi7](https://cloud.githubusercontent.com/assets/22547/6223495/66e630c6-b61f-11e4-980b-cdcdd458eab9.png)

If any of those speak to you in a way the one above doesn't, just let me know. Ah! Paradox of choice! (Sorry!)

**Comment by Roenok** [comment]
@charliepark They all look beautiful! Also, I can't actually tell the difference between most of them :)

@Cara-Jo Do you have a preference? You have a better eye for brand.

**Comment by Cara-Jo** [comment]
I like the top two the best! But I would love to see what the second two look like in the browser. @charliepark can you provide examples of that?

**Comment by charliepark** [comment]
Can do, but will have to wait until tonight. Thanks, both, for the feedback!

**Comment by charliepark** [comment]
Actually, will have to wait a few more days. Crazy deadlines at work. Promise to get this for you, though!

**Comment by kstack7** [comment]
We appreciate the help, @charliepark !

**Comment by charliepark** [comment]
Okay, here's the second two from the list, next to one of the first ones (on the far right).
![screen shot 2015-02-23 at 10 02 46 pm](https://cloud.githubusercontent.com/assets/22547/6344061/c68ee04e-bba7-11e4-8b52-8f2769d06182.png)

Thoughts welcome!

**Comment by kstack7** [comment]
I like gdi3 the most, @charliepark :) Any designers want to chime in? @Cara-Jo?

**Comment by charliepark** [comment]
Was thinking a bit more; the flourish is really a nice element. Here's one more option while waiting for any other input. I like the simplicity of this one.

![screen shot 2015-03-01 at 8 14 32 am](https://cloud.githubusercontent.com/assets/22547/6431644/1b574eee-bfeb-11e4-86f2-90f32b9326a2.png)

At this point, I'm cool with any direction; just let me know and I'll get the PR pulled together.

**Comment by Roenok** [comment]
@charliepark I like just the flourish best. I also think it will scale to different sizes a little more cleanly.

**Comment by charliepark** [comment]
Cool, @Roenok, me, too. Will use that one for the PR. Thanks!
