### ISSUE TITLE
Suggestion: Increase font size in top nav menu

### ISSUE THREAD

**Issue by Roenok** [girldevelopit/gdi-new-site#242]
**Description**
The current font size for the top nav menu, 14px, is small enough that I have trouble reading it on my laptop

**Ask**
Increase menu font to 16px, the body font size

**To Do**
- [ ] Increase menu font size (in Sass files, under header nav a)
- [ ] Test across browsers and view ports

**Additional Info**
Mockup is below. Design suggestions welcome!
![increased-header](https://cloud.githubusercontent.com/assets/925963/6220495/0581c616-b605-11e4-830e-2bef75980d6b.png)

**Comment by juliaelman** [comment]
@Roenok +1 I think we should make the Twitter and Facebook icons bigger too! Okay with you to add to the issue description?

**Comment by Cara-Jo** [comment]
I can do this as well as the link color in one sweep.

**Comment by Roenok** [comment]
Sure!

**Comment by kstack7** [comment]
Closed with #247
