### ISSUE TITLE
Add Link to New Chapter Interest Form

### ISSUE THREAD

**Issue by mmcelaney** [girldevelopit/gdi-new-site#244]
Description
The old site included a link to the new chapter interest form in the footer.

Ask
Add a link to the new chapter interest form to make it easier for people to contact HQ who want to start a new chapter!

To Do
I've already created a pull request with this change. 
https://github.com/girldevelopit/gdi-new-site/pull/243
Please check my pull request and confirm all is well!

**Comment by kstack7** [comment]
Hey @mmcelaney...just need ya to add a ">" to the opening <a> and then we're good to go!

**Comment by mmcelaney** [comment]
Done!
