### ISSUE TITLE
Add to contributor docs on how to format issues

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#245]
**Description**
*There have been several instances where a contributor has needed to re-format their newly issue.*

**Ask**
*Create a more seamless way for contributors to understand to use the #83 template when formatting issues.*

**To Do**
- [x] Add clearer instructions on reading the [contributors section on the docs](http://gdi-new-site.readthedocs.org/en/latest/sources/contribution/) before submitting an issue.
- [x] Add either a link to the template on Github and/or an example of the template in the docs.
- [x] Complete/Fix

**Additional Info**
*Original request was based off this comment by @lozandier: https://github.com/girldevelopit/gdi-new-site/issues/240#issuecomment-74574108*

**Comment by pamelafox** [comment]
I think you could probably put the template inside ``` code formatting so that people could copy/paste the markdown? Or stick it in a gist?

**Comment by juliaelman** [comment]
@pamelafox +1 on the gist and making it easier for folks to copy/pasta. We probably also want take into consideration that folks might want to see what the final result will look too. #83 can serve as that example :tada:

**Comment by kstack7** [comment]
@Cara-Jo offered her gist here: https://gist.github.com/Cara-Jo/ac8f3168db2a08317a13

Definitely helps to get feedback on what's easier

**Comment by juliaelman** [comment]
@kstack7 @Cara-Jo YES! Awesomeness. Since this issue is about adding to contributor docs, I think it'd be good to add that code into the docs. :+1:

**Comment by kstack7** [comment]
I think this issue can be knocked out by adding a CONTRIBUTING.md file per @DBNess suggestion in #318 :)

I pushed the file to staging if anyone wants to review/check it out!

**Comment by kstack7** [comment]
Closed with #323
