### ISSUE TITLE
Hide maps on meetup pages per Meetup settings or remove maps

### ISSUE THREAD

**Issue by pamelafox** [girldevelopit/gdi-new-site#248]
**Description**

Our chapter uses the meetup setting " Only my members can see where this Meetup is happening", however the maps still display. We hide location in case of creepsters, we try to make it a little less obvious where to find us, and the maps make it really easy. 

**Ask**
Can we have the chapter pages obey that setting, or remove the maps for now?

**Steps**
- [ ] Decide which ask to do
- [ ] Either make maps obey setting or remove them

**Comment by kstack7** [comment]
Thanks, @pamelafox...can you do us a favor and reformat the issue to match the template in #83 ? This  helps us stay consistent with our issues and what needs to happen.

**Comment by pamelafox** [comment]
Okay, fyi, copying/pasting that issue removes the formatting from it, and I can't edit to view the markdown, so I'll have to guess it, from what I can tell.

**Comment by kstack7** [comment]
Yeah we know the template ordeal is a bit clunky. We're hoping to cover that in #245 with some better ideas :)

**Comment by minamarkham** [comment]
How about using two layouts for classes, one with a map and one without?

Something like this:

![screen shot 2015-02-17 at 10 55 52 am](https://cloud.githubusercontent.com/assets/876210/6232721/93de1b88-b693-11e4-925f-017bf3a62cbe.png)

**Comment by juliaelman** [comment]
@minamarkham love it!

**Comment by Cara-Jo** [comment]
I REALLY love the bottom version with the tag next to it. I'm just concerned that as the site scales across devices the little banner might get a bit wonky and interfere with usability. I love that the little tab (bottom) will scale easily across all devices and is clean looking.

**Comment by minamarkham** [comment]
Best of both?

![screen shot 2015-02-17 at 12 25 11 pm](https://cloud.githubusercontent.com/assets/876210/6234380/1b1ddb54-b6a0-11e4-9fa5-2a1b03f133cc.png)

**Comment by kstack7** [comment]
I'm liking this one, @minamarkham ...is that a working example or a design layout?

**Comment by minamarkham** [comment]
It was an in the browser mockup. I still have the page open though :)

**Comment by minamarkham** [comment]
@kstack7 How do I get meetup/maps working in my local environment so I can start working on this?

**Comment by kstack7** [comment]
@minamarkham do you have an API key from your own meetup account that you could use? Once you get that then you just need to set the MEETUP_API_KEY variable in your local environment:

https://secure.meetup.com/meetup_api/key/

**Comment by minamarkham** [comment]
Yeah, I did that, and it's not working :disappointed:

**Comment by kstack7** [comment]
@minamarkham make sure you're in your local site directory and in terminal you can type the following:

export MEETUP_API_KEY=[your api key]

I just ran through it again to make sure the latest files aren't wonky. We can get on a quick Hangout if that doesn't seem to work so let me know!

**Comment by minamarkham** [comment]
@kstack7 Yeah, let's hangout. It's a no go for me.

**Comment by kstack7** [comment]
Alrighty I'm going to PR the "show/no show" based on permissions changes since that's more of a bug and then @minamarkham will tag team from there to do this sold out fun. This area has a lot of potential changes thus I want to make sure we iterate through them smoothly.
