### ISSUE TITLE
Create a staging instance of girldevelopit.com

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#249]
**Description**
*We currently only have a production instance running and are continuously deploying to it throughout each PR.*

**Ask**
*Create a staging instance on Heroku of the current website.*

**To Do**
- [x] Add a new application to to Heroku
- [x] Add the current codebase to that instance
- [x] Add most recent data to the instance

**Additional Info**
*We'll want to re-visit the way we merge/test any future change sets using this instance (e.g. @Roenok idea for a testing plan)*

**Comment by juliaelman** [comment]
@kstack7 staging instance is now updated with the latest db dump from production. https://girl-develop-it-staging.herokuapp.com/ I am going to close this issue, but please let me know if you'd like me to help build out this process and/or need anything else! :rocket:

**Comment by kstack7** [comment]
Hooray! Thank you, @juliaelman ...I was hitting some admin walls trying to tie it over to heroku so I'm glad you handled this...
