### ISSUE TITLE
Add Newsletter Signup form to homepage

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-new-site#256]
**Description**
*Add newsletter subscription sign up to homepage*

**Ask**
*Embed Mailchimp's Super Slim Form  "Subscribe to our Newsletter" on Homepage footer*

**To Do**
- [ ] Add embed code to home page

**Comment by kstack7** [comment]
Do we want to design out the form a bit or put it in any particular order? UX/Designers attack!

This is the Mailchimp default look for reference:

![screen shot 2015-02-23 at 8 14 51 pm](https://cloud.githubusercontent.com/assets/6612770/6341467/a9f45d60-bb98-11e4-9baa-c401eea88750.png)

**Comment by corinnepw** [comment]
@kstack7 I'd say let's just get it up if we can tonight (to be ready for the AOL push tomorrow) and we can make it prettier later... think it's possible to get it up tonight?

**Comment by kstack7** [comment]
![screen shot 2015-02-23 at 9 42 11 pm](https://cloud.githubusercontent.com/assets/6612770/6342301/d9ed71e4-bba4-11e4-9815-4004629ac893.png)

**Comment by kstack7** [comment]
I had the input aligned with the button for a hot second, but I never trust that across browsers haha

**Comment by corinnepw** [comment]
Awesome! Let's do it @kstack7

**Comment by Roenok** [comment]
Just tried it and it worked!
