### ISSUE TITLE
Memory leaks with Ruby 2.1.2

### ISSUE THREAD

**Issue by kstack7** [girldevelopit/gdi-new-site#257]
**Description**
*We have been noticing a number of "memory leak/exceeded memory limit" warnings in our logs this week. Only pattern so far is that it seems to occur around 4PM and more often around the chapter pages.*

**Ask**
*Find if the memory leaks are due to our code of if we should roll back to Ruby 2.0.0 (see links below)*

**To Do**
- [ ] Research exceeded memory errors on Heroku
- [ ] Analyze gemfile and look for potential memory hogs
- [ ] Implement the solution that will reduce memory usage

**Additional Info**
Useful threads: 
- https://discussion.heroku.com/t/memory-leaks-with-ruby-2-1-2/644/3
- http://blog.skylight.io/hunting-for-leaks-in-ruby/

**Comment by kstack7** [comment]
I rolled my local version back to Ruby 2.0.0 to see if we can attempt any minimal-change approaches and so far it's fine. Could be our fast fix while we explore ways of optimizing the code.

**Comment by bayendor** [comment]
FWIW, I have run this in a branch on Ruby 2.2.0 which implements several memory, GC, and symbol collection improvements, and have had no apparent problems.  At a bare minimum we could update to Ruby 2.1.3 which would introduce no breaking changes, and I believe addressed the memory leak issues in 2.1.2, jump to 2.1.5.

**Comment by westonplatter** [comment]
I second @bayendor's suggestion to migrate up towards 2.1.5

Is there a staging site that we could deploy a Ruby upgrade to in order to see if that fixes the issue?

**Comment by kstack7** [comment]
Hey there, @westonplatter! We do have a staging site/repo, but this leak is no longer a major issue since we have a better hosting setup than when we started. We're open to trying it!

**Comment by westonplatter** [comment]
@kstack7 awesome! If you're open to giving it a shot, how about I push suggested changes to the staging branch. Do you have access to deploy that branch to Heroku - or would I need to work with someone else?

**Comment by kstack7** [comment]
@westonplatter I do have access to deploy. Do you anticipate any drastic changes or a subtle upgrade?

**Comment by westonplatter** [comment]
@kstack7 I usually underestimate scope of code changes :).

I think the only reason changes would become drastic is if any of the ruby gems also needed upgrades to support the 2.1.2 -> 2.1.5 migration. I don't think this will be the case, but I not sure. I'll pull together the PR tonight we we can see the scope of the changes in the PR.

**Comment by kstack7** [comment]
@westonplatter sounds lovely! :+1:

**Comment by westonplatter** [comment]
@kstack7 ok, got a PR in. Happy to help with whatever you need to get it through!

**Comment by kstack7** [comment]
Thank you, @westonplatter :) I've pushed the changes on staging and am getting some extra eyes on the site to see that all is well. We appreciate your help!!!

https://girl-develop-it-staging.herokuapp.com/
