### ISSUE TITLE
New Chapters not added to locs2.yml file

### ISSUE THREAD

**Issue by gkimbwala** [girldevelopit/gdi-new-site#274]
Description
In reference to issue #240,  new chapters need to be hard coded into the locs2.yml file. The chapter_seed variable references the yml file to create new entry in the database but does not create any new entries that are not on the locs2.yml file.

Ask
To remedy the issue you would have to utilize the Meetup API to gather all the need information about the different states in the database. 

To Do

config all the new Chapters information utlizing the MeetupAPI for any missing information. 
other than that I have no clue!
Tried to start hardcoding the information but could not get all the organizer information needed.

**Comment by Roenok** [comment]
Hey @gkimbwala, that seed data is only for testing/local environments. New chapters join the production database
