### ISSUE TITLE
Sponsors do not display on chapter pages on mobile 

### ISSUE THREAD

**Issue by beckysingson** [girldevelopit/gdi-new-site#284]
**Description**
When viewing chapter pages on mobile, sponsor logos do not display. 

**Ask**
Update mobile media queries to include sponsor logos on mobile device/screen widths. It looks like mobile was part of the ask in #171 but not sure if it wasn't included or if this display issue is a bug. 

**To Do**
- [x] Confirm if sponsors section was added or not to mobile styles
- [x] Add and/or debug issue causing sponsor logos not to display 

**Additional Info**
![img_0648_png_and_cincinnati_-_girl_develop_it](https://cloud.githubusercontent.com/assets/1359661/6543635/591bae18-c4f1-11e4-91a7-a33bd742aef2.png)

**Comment by kstack7** [comment]
Hey there, @beckysingson...the sponsors appear to be built into a "hide" class, which is programmed to disappear on widths smaller than 500px. So we definitely could use a mobile-friendly layout for the sponsors. 

Thanks for posting the issue!

**Comment by juliaelman** [comment]
Fixed with #298 by @celeen!
