### ISSUE TITLE
Social media icons are wonky

### ISSUE THREAD

**Issue by therufs** [girldevelopit/gdi-new-site#286]
Description
Chrome / OSX 10.9.5: some social media icons aren't showing up (Twitter, LinkedIn, Facebook.)  The links are still there. 

In the dev console, it looks like the correctly displayed icons have ::before inside the <i> tag, and the incorrectly displayed ones don't. 

Ask
Desired behavior: have them show up! 

To Do
- [ ] ??? It's not obvious to me from the erb why this is happening. :/ 

![chap icons](https://cloud.githubusercontent.com/assets/4154345/6567950/3bbc837c-c6a6-11e4-94a1-fe24fb10af2d.png)

![personal icons](https://cloud.githubusercontent.com/assets/4154345/6567949/3bbb6c6c-c6a6-11e4-9acc-3acf27565560.png)

**Comment by kstack7** [comment]
O_o well that's a fun one...sniffing this out

**Comment by kstack7** [comment]
Can anyone else on 10.9.5 recreate this?

**Comment by juliaelman** [comment]
@therufs hrmmm... this works for me! //cc @kstack7 Here are the browsers I tested it in:

Chrome Version 41.0.2272.89 (64-bit)
Firefox 36.0.1
Safari 8.0.3

Also using OS Yosemite 10.10.2

**Comment by jenfinery29** [comment]
Can't recreate this bug either.  Checked in:
Chrome 41.0.2272.89
Firefox 35.0.1
Safari 7.1.4

**Comment by juliaelman** [comment]
@kstack7 we've had a few folks say that they are not able to recreate the issue. What do you think best next steps are?

**Comment by therufs** [comment]
I'm wondering whether this might actually be a bug in Chrome?

**Comment by kstack7** [comment]
Yeah this one is intriguing me... @therufs are you able to update or anything? Curious if it's just your installation? I tapped into my work network and snagged a computer on 10.9.5 to try this and could not recreate the issue. Do you know which version of Chrome you're on or if you can do this in a different browser?

![screen shot 2015-03-22 at 5 16 12 pm](https://cloud.githubusercontent.com/assets/6612770/6771542/58ede560-d0b7-11e4-8c0b-aa0aabd78f15.png)
![screen shot 2015-03-22 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/6612770/6771541/58ede538-d0b7-11e4-9134-4969b1b6e098.png)

**Comment by therufs** [comment]
Current Chrome version: 41.0.2272.89 

Am I able to update (I assume we mean to OSX 10.10): yes but I'm dragging my feet because Yosemite gives me uncanny valley feels >.< 

If literally no one else is having this problem, I'm glad to go on record as saying it does not detract from the site's functionality or loveliness enough to be worth chasing further. :)

**Comment by kstack7** [comment]
Oh, I was definitely only referring to updating Chrome :) I wouldn't want to impose OS versions on ya haha Yosemite still has some quirks to iron out. Though, I notice the 10.9 I used to try out Chrome was on Version 41.0.2272.101...seems like yours is a smidge behind in that regard. Are you able to update your Chrome and see if it's still there? If not, we may fly the "this is a small percentage of folks" flag and carry on :)

**Comment by therufs** [comment]
I'm updated, no dice. Weird city!  ¯(°_o)/¯

**Comment by kstack7** [comment]
Geez I'm not so sure then...I did task some of the chapter leaders to test it out in tonight's chapter leader meeting so we'll see if anyone else finds it...otherwise, we may have to scratch it up to a weird fluke. Thanks for checking!

**Comment by kstack7** [comment]
Going to chalk this one up to a fluke instance and close. :+1:
