### ISSUE TITLE
Clarify use of seed data

### ISSUE THREAD

**Issue by therufs** [girldevelopit/gdi-new-site#287]
Description
locs2.yml isn't meant to be the canonical repository of extant chapters, but people are getting confused. 

Ask
I think it would be a good idea to cut it down to just a chapter or two. (Where was the first chapter? Are there any other obvious ones to pick?) 

To Do
- [x] Annotate locs2.yml 
- [x] Remove most chapters 
- [x] Update docs 

<3

**Comment by therufs** [comment]
(I'll work on this!)

**Comment by Roenok** [comment]
NYC was the first chapter, SF is probably the largest

**Comment by kstack7** [comment]
Good idea, @therufs...definitely no need to chase our tails on this if we can help everyone see what the purpose is here...

**Comment by therufs** [comment]
:idea: If we add locs2.yml to .gitignore, everyone can pull down the trimmed version and seed back in their own chapter as it makes them happy to do! Thoughts?
