### ISSUE TITLE
Add a 'More Events' link to chapter pages

### ISSUE THREAD

**Issue by techibis** [girldevelopit/gdi-new-site#291]
Description
After the three events that are listed on the chapter pages, create a text link that says 'More Events' and that leads to the chapter's meetup home page.  This is quite important for chapters with extended areas.

Ask
Link appears on chapter pages and takes you to the chapter's meetup home page.

To Do
* Add link to chapter page

Additional Info
Use Case:  The next three events may not be in my part of town, but I want to see if any others are.

**Comment by juliaelman** [comment]
Hi @techibis and thanks for submitting the issue! Would you mind reformatting your issues description with the following template #83?

**Comment by techibis** [comment]
Updated.

**Comment by keaty** [comment]
Hi @techibis and @juliaelman, I've submitted a pull request for this issue. Let me know if you'd like different language for the link, different link placement, etc.

**Comment by juliaelman** [comment]
@keaty solved the issue! :rainbow:
