### ISSUE TITLE
Add sponsor and partner logos

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-new-site#292]
**Add attached logos to sponsors page**

*Add sponsor DuckDuckGo logo and partner CodeMontage logo*
Sponsor ![ddg-logo_full-horizontal-01](https://cloud.githubusercontent.com/assets/4427638/6631902/0835b89c-c904-11e4-8a28-954b0d6a79bc.png)
link to http://duckduckgo.com

Partner:
![codemontagelogo](https://cloud.githubusercontent.com/assets/4427638/6632026/1dc99ca8-c906-11e4-90c0-1d1854b067ba.png)
link to http://codemontage.com

**Comment by kstack7** [comment]
Fixed by PR #295

**Comment by kstack7** [comment]
Thank you to @annakaringal for your first-time contribution!
