### ISSUE TITLE
Add SSL certificate and validate

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#60]
We need to purchase and validate an SSL cert. @DBNess has a discount code for purchasing one, but there are also free ways to receive the certificate: https://www.startssl.com/

I also did some research and it looks like Heroku will charge us $20/month for SSL: https://addons.heroku.com/ssl

Here are the steps we need to take to move foward:

- [x] Determine whether we purchase a certificate OR we use https://www.startssl.com/
- [x] Add SSL certificate to our Heroku instance
- [x] Validate https://www.expeditedssl.com/simple-ssl-scanner/

**Comment by kstack7** [comment]
@juliaelman did we purchase?

**Comment by juliaelman** [comment]
@kstack7 we got a free one and will be happy to fwd you the information if you'd like to tackle this!

**Comment by juliaelman** [comment]
Done and verified! :rocket:
