### ISSUE TITLE
Create new donations page

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#62]
The current sponsorship page has limited capacity for making custom donation amounts. We'd like to create the ability for companies and individuals to be able to contribute donations more easily. Here are the following steps we'll need to take to help make this happen on the new site:

- [x] Sketch/wireframe the layout for the new page
- [x] Receive updated code from our Amazon account that allows for custom donations
- [x] Create route to "/donate"
- [x] Add link to new "Donate" page in navigation structure
- [x] Add new template and styling for donations page

**Comment by kstack7** [comment]
Hey there...I have '/donate' routing to a new view in the home folder, but am curious where you'd like the link in the navigation. Is there a designed example for me to reference?

Also, should I create a PR for this new page or can I add the navigation changes to this, too?

**Comment by juliaelman** [comment]
(Keeping a note in here to FTR).

@kstack7 is working on the routing + link addition for the new donation page. 

@Cara-Jo there is some config stuff in regards to the Amazon donate config that needs to be implemented on the page. I'll get that in place and then pass off to you to work you design magic! \o/

**Comment by juliaelman** [comment]
Partial fix here #116.

**Comment by Cara-Jo** [comment]
@juliaelman I can wait until the slider and form stuff are in place before working some design magic.

**Comment by corinnepw** [comment]
@juliaelman see content for /donate here: https://docs.google.com/a/girldevelopit.com/document/d/1tjcTUloyxVSSK1pOUHENmRWa2hsOySwJdUsv2PhSzNw/edit?usp=sharing
What additional content is needed for the donate page? Suggested levels? or "this is what x amount supports" on the slider?

**Comment by juliaelman** [comment]
**UPDATE** HQ decided to change from using Amazon to Paypal for the donation page. 

@Cara-Jo I am going to submit a PR that go with #116 and adds the simple "Donate" Paypal that we've used in the past. I'll let you work your :sparkles: to make it look even better (e.g. create custom button image/code).

**Comment by juliaelman** [comment]
@corinnepw awesome! You rule and thanks for getting that copy together so quickly. I'll leave it to @Cara-Jo to incorporate it into her design for the page.

**Comment by juliaelman** [comment]
@Cara-Jo re-assigning to you so that you can work your design :sparkles: to this page! \o/

**Comment by Cara-Jo** [comment]
PR #183. :muscle: :sparkles:

**Comment by kstack7** [comment]
Merged PR #183, but curious if we have anyone on deck to tackle the copy? @corinnepw @juliaelman ?

**Comment by juliaelman** [comment]
@kstack7 I assumed @Cara-Jo would do something with that in her design work on this issue.

Does that sound right @Cara-Jo?

**Comment by Cara-Jo** [comment]
Pretty sure I was just supposed to style the button? I’m not a copywriter and there is no copy for this page. 

-- 
CARA JO MILLER | Co-founder | Girl Develop It Boulder/Denver | 248.230.0910 | carajo@girldevelopit.com | girldevelopit.com | @GDIboulder | @GDIDenver | @corrinajo

On February 6, 2015 at 10:09:04 AM, Julia Elman (notifications@github.com) wrote:

@kstack7 I assumed @Cara-Jo would do something with that in her design work on this issue.

Does that sound right @Cara-Jo?

**Comment by juliaelman** [comment]
@Cara-Jo bah! Sorry for the confusion. @corinnepw created copy around 10 days ago (see comment above) and you can find it here: 

https://docs.google.com/a/girldevelopit.com/document/d/1tjcTUloyxVSSK1pOUHENmRWa2hsOySwJdUsv2PhSzNw/edit

**Comment by kstack7** [comment]
I actually talked to @corinnepw about this earlier this morning...she linked me here: https://docs.google.com/a/girldevelopit.com/document/d/1tjcTUloyxVSSK1pOUHENmRWa2hsOySwJdUsv2PhSzNw/edit

**Comment by kstack7** [comment]
Haha jinx @juliaelman ... @corinnepw and I went over what makes sense so she updated the paragraphs to reflect the page as it is right now. I can add the copy in if we're all cool with it?

**Comment by juliaelman** [comment]
@kstack7 cool :penguin:

**Comment by juliaelman** [comment]
#192 completes a simple version of the donations page. We should definitely keep track of this issue to help build out this page a bit more!

**Comment by pxh1432** [comment]
An interesting aspect that that may be beneficial is showing examples of the results of the donations.  Like examples of "see where your money goes!" 

 Maybe have an image 
-Thanks to contributions made by amazing people like you...we were able to...!

**Comment by corinnepw** [comment]
@alohaas reviving this! How well do you think the second version of the slider (minus "which chapter" field) would go at the bottom of the updates made in #397?
