### ISSUE TITLE
Add updated Google Analytics code

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#63]
Pending on #61

**Comment by juliaelman** [comment]
From @Roenok:

From our current production site, the UA-code is UA-19096645-1

```javascript
<script type="text/javascript" async="" src="http://www.google-analytics.com/ga.js"></script>

<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19096645-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
```

**Comment by juliaelman** [comment]
From @DBNess:

Yay analytics!! Can we set this up using an environment variable, so that
only the production site's visits are recorded to this tracking code? That
way people developing the site locally won't falsely affect our Google
Analytics numbers.

Here's a code example of how to set this up:

Frontend code references GOOGLE_ANALYTICS_TRACKING_CODE variable:
https://github.com/CodeMontageHQ/codemontage/blob/master/app/views/layouts/_google_analytics.html.erb

GOOGLE_ANALYTICS_TRACKING_CODE variable is defined per environment:
https://github.com/CodeMontageHQ/codemontage/blob/master/config/environments/production.rb
https://github.com/CodeMontageHQ/codemontage/blob/master/config/environments/development.rb

**Comment by kstack7** [comment]
@DBNess sure! @juliaelman & @Roenok do we have access to the analytics to get/create these two codes? I'd be happy to put this together if so...

**Comment by juliaelman** [comment]
@kstack7 done!

**Comment by kstack7** [comment]
Thanks for the input @DBNess ... This is set at PR #189
