### ISSUE TITLE
Create new sponsors page

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#64]
- [x] Write content for the page
- [x] Create link to email sponsorships@girldevelopit.com to contact us
- [x] Create route to "/sponsors"
- [x] Add link to new "Sponsors" page in navigation structure
- [x] Add new template and styling for sponsors page

**Comment by corinnepw** [comment]
See some content to use for now here: https://docs.google.com/a/girldevelopit.com/document/d/1tjcTUloyxVSSK1pOUHENmRWa2hsOySwJdUsv2PhSzNw/edit#

**Comment by juliaelman** [comment]
@corinnepw awesome! Thank you for getting the copywriting completed.

@minamarkham are you able to help out with the layout still? If so, let me know and will re-assign to ya!

**Comment by corinnepw** [comment]
@minamarkham awesome! Wanted to check in if you think you'll have time to help with layout before Friday (soft launch)? Thanks much! cc: @juliaelman

**Comment by minamarkham** [comment]
@corinnepw Yes I will. I'll submit a PR in tonight or tomorrow + @juliaelman

**Comment by corinnepw** [comment]
@minamarkham beautiful! Let me know if you need anything on my end - happy to provide any guidance. In fact, I can probably add some more language that I think will help...

**Comment by juliaelman** [comment]
@corinnepw can you provide a list of sponsors that should be included on the page? Wanting to make sure that @minamarkham has the correct information in that regard.

**Comment by juliaelman** [comment]
Done #207
