### ISSUE TITLE
Create new curriculum page

### ISSUE THREAD

**Issue by juliaelman** [girldevelopit/gdi-new-site#66]
This one is a little trickier, as we need to be thinking about how we maintain links to our official curriculum. Would love to hear thoughts from the curriculum team on the steps we need to take to complete this issue. //cc @Roenok @pamelafox

- [x] Sketch/wireframe the layout for the new page
- [x] Create route to "/materials"
- [x] Add link to new "Curriculum" page in navigation structure
- [x] Add new template and styling for curriculum page
- [x] Add intro content introducing how our curriculum is developed (include info on Creative Commons licensing, open source, etc)

**Comment by corinnepw** [comment]
Here's a draft of /curriculum intro note: https://docs.google.com/a/girldevelopit.com/document/d/1tjcTUloyxVSSK1pOUHENmRWa2hsOySwJdUsv2PhSzNw/edit#
I would love @Roenok to review/add to that if possible!

**Comment by Cara-Jo** [comment]
Love how Code School displays their 'tracks' for users. I think something like this for our materails would look slick with the new desing. 
![screenshot 2015-01-31 09 58 56](https://cloud.githubusercontent.com/assets/180763/5988904/1e575ad8-a931-11e4-9bff-4a30033c55c4.png)

**Comment by Roenok** [comment]
Thinking about something like that, but am I not sure if we can get together images/icons. Do you know of any repos, @Cara-Jo?

**Comment by Cara-Jo** [comment]
I know of this set: http://mfizz.com/oss/font-mfizz @Roenok

**Comment by Roenok** [comment]
Thanks @Cara-Jo! Those could be helpful. 

@juliaelman How much programming complexity will I be adding if I wireframe something with individual landing pages for each course? I want to make something we can actually build out. We can stick to accordions for now, if need be.

**Comment by juliaelman** [comment]
@Roenok I don't think it will be that complex and a fairly simple task. There would only really be two templates: one for a list of curriculum and one for individual curriculum pages. I think it would all depend on the complexity of the layout in general.

Looking forward to seeing your wireframes! :tada:

**Comment by Roenok** [comment]
Random thought: Can we preserve that canonical /materials URL for this page, either as the main URL or a redirect? I suspect there are a lot of incoming links out there.

**Comment by juliaelman** [comment]
@Roenok good point and important to note! Feel free to open another PR for this one, as we want to try to stay focused in scope on this issue. Thanks!

**Comment by Roenok** [comment]
Mockups are here: https://www.dropbox.com/s/8hhy98uihomesry/Curriculum%20Mockups.pdf?dl=0

Or PNGs dumped below:
![course page - desktop](https://cloud.githubusercontent.com/assets/925963/5989658/877a8b54-a95c-11e4-8b76-95e9c58dd15d.png)
![course page - mobile](https://cloud.githubusercontent.com/assets/925963/5989659/877b4698-a95c-11e4-9a5c-31bb199c421a.png)
![curriculum page - desktop](https://cloud.githubusercontent.com/assets/925963/5989657/8778f636-a95c-11e4-96c7-7c2a84a89366.png)
![curriculum page - mobile](https://cloud.githubusercontent.com/assets/925963/5989660/877c1ffa-a95c-11e4-9d06-5bc764de081b.png)

**Comment by kstack7** [comment]
Was just talking to @Roenok about building this page. She brought up a good point about shifting from 'curriculum' to 'materials' just to make it easier for folks to link/type/spell. We could still route all curriculum/materials links to the same page, but just have 'materials' as the primary name. This would knock out #135 as well. Thoughts?

**Comment by Roenok** [comment]
+1 on the URL change. The current curriculum page has pretty good SEO authority and a few hundred incoming links. Maintaining a canonical URL is good practice.

**Comment by Roenok** [comment]
Hey, @kstack7! More mockups, this time with confusing annotations. Field list is here:
https://docs.google.com/spreadsheets/d/1doNd2Q7qLKTd2rAx_0ZzSQdkpXWf44z1xW-HNfxeyJM/edit?usp=sharing

Annotated mockups are below
![course page - annotated](https://cloud.githubusercontent.com/assets/925963/6014116/819894d4-ab2c-11e4-980d-0e4ff996a897.png)
![Uploading Curriculum Page - Annotated.png . . .]()

**Comment by kstack7** [comment]
ooOOOoo thankya, @Roenok ! super helpful...I'll take a swing :)

**Comment by pamelafox** [comment]
FYI, for our SF curriculum on teaching-materials.org, I often have a "View teachers info" toggle at the top, that shows more detailed instructions, teacher notes, in-class examples, etc. You can see an example here: http://www.teaching-materials.org/htmlcss-1day/
That was how I resolved the tension between the 2 different audiences for the materials.

**Comment by kstack7** [comment]
Submitted PR #170 which includes ActiveAdmin role-related capabilities, routing, link added to navigation, and redirects for 'curriculum' or whichever...

I'm STILL getting a bit snarled up by seeing the designs say "curriculum" in the urls and discussing how the old site is at "materials"...which do we prefer? I'll need to swap up the database if we were hoping for curriculum haha because I developed it with "materials" :D so lemme know :+1:

**Comment by juliaelman** [comment]
@kstack7 we're wanting to stick with /materials to be consistent with the past linkage on the old site. Dis-regard the url in the mock-ups.

@Roenok are you planning on tackling the layout? Also, would it be possible to remove the mockups that say "Curriculum" with new one's that say "Materials"? Might help avoid any future confusion.

@pamelafox that is brilliant! Want to open an issue with this so we can add it to a later fix? Wanting to get something super simple ATM.

**Comment by Roenok** [comment]
@juliaelman Yep, I'm on front-end, once I get the dev environment up.

**Comment by kstack7** [comment]
@juliaelman  gladly! :) No changes then...

**Comment by kstack7** [comment]
yes, @Roenok , the pending changes include that curriculum redirect :)

**Comment by juliaelman** [comment]
@Roenok we just merged, deployed and migrated the new changes to the new materials page: https://girl-develop-it.herokuapp.com/materials You should be able to start adding materials into the DB now and can worry about styling once that data is in there.

Thanks for @kstack7 again for kicking :rocket:!

**Comment by Roenok** [comment]
Thanks @juliaelman and @kstack7. Content is under #136, so all that is left here is the front-end code. I'll write up some simple CSS. Any designers are invited to make it better.

**Comment by kstack7** [comment]
Just a heads up that I have PR #175 in the wings so you can pull down the views with db data in place (likely tomorrow) :+1:

**Comment by juliaelman** [comment]
Fixed #175
