### ISSUE TITLE
Selected State on Navigation

### ISSUE THREAD

**Issue by alohaas** [girldevelopit/gdi-new-site#68]
@alohaas pointed out that the current navigation does not provide a way for folks to know what page they are viewing. Here are some steps that might be useful in resolving this issue:

- [ ] Create a simple layout with the new indication
- [ ] Add the new HTML/CSS to the site

**Comment by alohaas** [comment]
I was thinking the simplest solution would be to mirror the hover state.
![screenshot 2015-01-28 09 59 35](https://cloud.githubusercontent.com/assets/4480279/5939754/6a33d756-a6d4-11e4-863b-342b3dc159eb.png)

**Comment by juliaelman** [comment]
:+1: on this solution @alohaas!

**Comment by AndyLampert** [comment]
I'm gonna work on this this afternoon!

**Comment by juliaelman** [comment]
Right on @AndyLampert! :dango:

**Comment by thejinxters** [comment]
Worked on with @AndyLampert, submitted pull request https://github.com/girldevelopit/gdi-new-site/pull/134

**Comment by juliaelman** [comment]
w00t! Done and closing <3
