### ISSUE TITLE
Update site design to match current brand

### ISSUE THREAD

**Issue by Cara-Jo** [girldevelopit/gdi-new-site#69]
* Update headline & body fonts
* Update photo on homepage to reflect current students.
* Have a repository of photos that can be used for the home page to keep it relevant
* Add photograph of students/leaders for the about page - because photos!

**Comment by juliaelman** [comment]
After a few discussions, we decided to remove this issue and break it down into smaller issues that are easier to handle/review with a single PR. (e.g. #114)
